import {
  AnalyticsCard,
  ExpertsCard,
  FAQ,
  FeaturedFreelancer,
  JobCard,
  JobRequirements,
  JobServiceDescription,
  JobSupport,
  MenuSection,
  PackageCard,
  PortfolioCard,
  ProfileData,
  RequesterDisputes,
  ReviewsCard,
  SkillsList,
  UserCard,
} from "@/interfaces/ServiceRequesterDashboard";

export const requesterMenuLinks: MenuSection[] = [
  {
    id: 1,
    title: "General",
    links: [
      {
        id: 1,
        icon: "/service-requester-dashboard/dashboard.svg",
        icon2: "/service-requester-dashboard/dashboard2.svg",
        label: "Dashboard",
        url: "?view=dashboard",
      },
      {
        id: 2,
        icon: "/service-requester-dashboard/jobs.svg",
        icon2: "/service-requester-dashboard/jobs2.svg",
        label: "Jobs",
        url: "?view=jobs",
      },
      {
        id: 3,
        icon: "/service-requester-dashboard/disputes.svg",
        icon2: "/service-requester-dashboard/disputes2.svg",
        label: "Disputes",
        url: "?view=disputes",
      },
      {
        id: 4,
        icon: "/service-requester-dashboard/messages.svg",
        icon2: "/service-requester-dashboard/messages2.svg",
        label: "Messages",
        url: "?view=messages",
      },
    ],
  },
  {
    id: 2,
    title: "Tools",
    links: [
      {
        id: 1,
        icon: "/service-requester-dashboard/payment.svg",
        icon2: "/service-requester-dashboard/payment2.svg",
        label: "Payment",
        url: "#",
      },
      {
        id: 2,
        icon: "/service-requester-dashboard/setting.svg",
        icon2: "/service-requester-dashboard/setting2.svg",
        label: "Settings",
        url: "?view=settings",
      },
      {
        id: 3,
        icon: "/service-requester-dashboard/faq.svg",
        icon2: "/service-requester-dashboard/faq2.svg",
        label: "FAQs",
        url: "?view=faqs",
      },
      {
        id: 4,
        icon: "/service-requester-dashboard/logout.svg",
        icon2: "/service-requester-dashboard/logout2.svg",
        label: "Logout",
        url: "#",
      },
    ],
  },
];

export const expertsCardData: ExpertsCard[] = [
  {
    id: 1,
    profileImg: "/service-requester-dashboard/profile.svg",
    name: "Saud Al-Faisal",
    occpation: "Expert Plumber",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 20,
    desc: "Reliable plumbing services with quick response time and high-quality repairs.",
    budgetImg: "/service-requester-dashboard/budget.svg",
    budget: "Budget",
    budgetValue: 100,
    locationImg: "/service-requester-dashboard/location.svg",
    location: "Location",
    locationVenue: "Riyadh, Saudi Arabia",
    skills: [
      { id: 1, label: "Pipe Repair" },
      { id: 2, label: "Leak fixing" },
      { id: 3, label: "Drain Cleaning" },
      { id: 4, label: "Bathroom Installations" },
      { id: 5, label: "Water Heater Installation" },
      { id: 6, label: "Fixture Replacement" },
      { id: 7, label: "Sewer Line Services" },
      { id: 8, label: "Emergency Plumbing" },
    ],
    button: "Send Job Request",
  },
  {
    id: 2,
    profileImg: "/service-requester-dashboard/profile2.svg",
    name: "Ahmed Bin Zayed",
    occpation: "Expert Plumber",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 20,
    desc: "Reliable plumbing services with quick response time and high-quality repairs.",
    budgetImg: "/service-requester-dashboard/budget.svg",
    budget: "Budget",
    budgetValue: 100,
    locationImg: "/service-requester-dashboard/location.svg",
    location: "Location",
    locationVenue: "Riyadh, Saudi Arabia",
    skills: [
      { id: 1, label: "Pipe Repair" },
      { id: 2, label: "Leak fixing" },
      { id: 3, label: "Drain Cleaning" },
      { id: 4, label: "Bathroom Installations" },
      { id: 5, label: "Water Heater Installation" },
      { id: 6, label: "Fixture Replacement" },
      { id: 7, label: "Sewer Line Services" },
      { id: 8, label: "Emergency Plumbing" },
    ],
    button: "Send Job Request",
  },
  {
    id: 3,
    profileImg: "/service-requester-dashboard/profile2.svg",
    name: "Fatima Al-Nasser",
    occpation: "Expert Plumber",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 20,
    desc: "Reliable plumbing services with quick response time and high-quality repairs.",
    budgetImg: "/service-requester-dashboard/budget.svg",
    budget: "Budget",
    budgetValue: 100,
    locationImg: "/service-requester-dashboard/location.svg",
    location: "Location",
    locationVenue: "Riyadh, Saudi Arabia",
    skills: [
      { id: 1, label: "Pipe Repair" },
      { id: 2, label: "Leak fixing" },
      { id: 3, label: "Drain Cleaning" },
      { id: 4, label: "Bathroom Installations" },
      { id: 5, label: "Water Heater Installation" },
      { id: 6, label: "Fixture Replacement" },
      { id: 7, label: "Sewer Line Services" },
      { id: 8, label: "Emergency Plumbing" },
    ],
    button: "Send Job Request",
  },
  {
    id: 4,
    profileImg: "/service-requester-dashboard/profile2.svg",
    name: "Omar Al-Khalid",
    occpation: "Expert Plumber",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 20,
    desc: "Reliable plumbing services with quick response time and high-quality repairs.",
    budgetImg: "/service-requester-dashboard/budget.svg",
    budget: "Budget",
    budgetValue: 100,
    locationImg: "/service-requester-dashboard/location.svg",
    location: "Location",
    locationVenue: "Riyadh, Saudi Arabia",
    skills: [
      { id: 1, label: "Pipe Repair" },
      { id: 2, label: "Leak fixing" },
      { id: 3, label: "Drain Cleaning" },
      { id: 4, label: "Bathroom Installations" },
      { id: 5, label: "Water Heater Installation" },
      { id: 6, label: "Fixture Replacement" },
      { id: 7, label: "Sewer Line Services" },
      { id: 8, label: "Emergency Plumbing" },
    ],
    button: "Send Job Request",
  },
  {
    id: 5,
    profileImg: "/service-requester-dashboard/profile2.svg",
    name: "Laila Al-Farouq",
    occpation: "Expert Plumber",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 20,
    desc: "Reliable plumbing services with quick response time and high-quality repairs.",
    budgetImg: "/service-requester-dashboard/budget.svg",
    budget: "Budget",
    budgetValue: 100,
    locationImg: "/service-requester-dashboard/location.svg",
    location: "Location",
    locationVenue: "Riyadh, Saudi Arabia",
    skills: [
      { id: 1, label: "Pipe Repair" },
      { id: 2, label: "Leak fixing" },
      { id: 3, label: "Drain Cleaning" },
      { id: 4, label: "Bathroom Installations" },
      { id: 5, label: "Water Heater Installation" },
      { id: 6, label: "Fixture Replacement" },
      { id: 7, label: "Sewer Line Services" },
      { id: 8, label: "Emergency Plumbing" },
    ],
    button: "Send Job Request",
  },
  {
    id: 6,
    profileImg: "/service-requester-dashboard/profile2.svg",
    name: "Hassan Al-Mutairi",
    occpation: "Expert Plumber",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 20,
    desc: "Reliable plumbing services with quick response time and high-quality repairs.",
    budgetImg: "/service-requester-dashboard/budget.svg",
    budget: "Budget",
    budgetValue: 100,
    locationImg: "/service-requester-dashboard/location.svg",
    location: "Location",
    locationVenue: "Riyadh, Saudi Arabia",
    skills: [
      { id: 1, label: "Pipe Repair" },
      { id: 2, label: "Leak fixing" },
      { id: 3, label: "Drain Cleaning" },
      { id: 4, label: "Bathroom Installations" },
      { id: 5, label: "Water Heater Installation" },
      { id: 6, label: "Fixture Replacement" },
      { id: 7, label: "Sewer Line Services" },
      { id: 8, label: "Emergency Plumbing" },
    ],
    button: "Send Job Request",
  },
];

export const searchOptions = ["Rating", "Reviews", "Price", "Newest", "Oldest"];

export const requesterJobAnalyticsData: AnalyticsCard[] = [
  {
    id: 1,
    label: "Posted Jobs",
    value: 12,
  },
  {
    id: 2,
    label: "On Going Contracts",
    value: 7,
  },
  {
    id: 3,
    label: "Order Completion Rate",
    value: 99,
    unit: "%",
  },
  {
    id: 4,
    label: "Total Spendings",
    value: 500,
    unit: "SAR",
  },
];

export const userCardData: UserCard[] = [
  {
    id: 1,
    bgImg: "/service-requester-dashboard/cover.svg",
    heartImg: "/service-requester-dashboard/heart.svg",
    profileImg: "/service-requester-dashboard/profile.svg",
    status: "online",
    name: "Saud Al-Faisal",
    desc: "Fast and reliable plumbing solutions at your doorstep!",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 19,
    startingFrom: "Starting from",
    value: 100,
  },
  {
    id: 2,
    bgImg: "/service-requester-dashboard/cover.svg",
    heartImg: "/service-requester-dashboard/heart.svg",
    profileImg: "/service-requester-dashboard/profile.svg",
    status: "offline",
    name: "Saud Al-Faisal",
    desc: "Fast and reliable plumbing solutions at your doorstep!",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 19,
    startingFrom: "Starting from",
    value: 100,
  },
  {
    id: 3,
    bgImg: "/service-requester-dashboard/cover.svg",
    heartImg: "/service-requester-dashboard/heart.svg",
    profileImg: "/service-requester-dashboard/profile.svg",
    status: "online",
    name: "Saud Al-Faisal",
    desc: "Fast and reliable plumbing solutions at your doorstep!",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 19,
    startingFrom: "Starting from",
    value: 100,
  },
  {
    id: 4,
    bgImg: "/service-requester-dashboard/cover.svg",
    heartImg: "/service-requester-dashboard/heart.svg",
    profileImg: "/service-requester-dashboard/profile.svg",
    status: "offline",
    name: "Saud Al-Faisal",
    desc: "Fast and reliable plumbing solutions at your doorstep!",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 19,
    startingFrom: "Starting from",
    value: 100,
  },
  {
    id: 5,
    bgImg: "/service-requester-dashboard/cover.svg",
    heartImg: "/service-requester-dashboard/heart.svg",
    profileImg: "/service-requester-dashboard/profile.svg",
    status: "online",
    name: "Saud Al-Faisal",
    desc: "Fast and reliable plumbing solutions at your doorstep!",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 19,
    startingFrom: "Starting from",
    value: 100,
  },
  {
    id: 6,
    bgImg: "/service-requester-dashboard/cover.svg",
    heartImg: "/service-requester-dashboard/heart.svg",
    profileImg: "/service-requester-dashboard/profile.svg",
    status: "offline",
    name: "Saud Al-Faisal",
    desc: "Fast and reliable plumbing solutions at your doorstep!",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 19,
    startingFrom: "Starting from",
    value: 100,
  },
  {
    id: 7,
    bgImg: "/service-requester-dashboard/cover.svg",
    heartImg: "/service-requester-dashboard/heart.svg",
    profileImg: "/service-requester-dashboard/profile.svg",
    status: "online",
    name: "Saud Al-Faisal",
    desc: "Fast and reliable plumbing solutions at your doorstep!",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 19,
    startingFrom: "Starting from",
    value: 100,
  },
  {
    id: 8,
    bgImg: "/service-requester-dashboard/cover.svg",
    heartImg: "/service-requester-dashboard/heart.svg",
    profileImg: "/service-requester-dashboard/profile.svg",
    status: "offline",
    name: "Saud Al-Faisal",
    desc: "Fast and reliable plumbing solutions at your doorstep!",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 19,
    startingFrom: "Starting from",
    value: 100,
  },
];

export const activeJobsData: JobCard[] = [
  {
    id: 1,
    title: "House Cleaning & Roofing Maintenance Needed",
    price: "Order Price",
    jobPrice: 200,
    duration: "Duration",
    jobDuration: 3,
    orderStarted: "Order Started",
    jobStartedDate: "Mar 05, 2025",
    provider: "Hired Provider",
    jobProviderName: "Saud Al-Faisal",
    status: "Ongoing",
    view: "View",
  },
  {
    id: 2,
    title: "Garden Landscaping Required",
    price: "Order Price",
    jobPrice: 350,
    duration: "Duration",
    jobDuration: 5,
    orderStarted: "Order Started",
    jobStartedDate: "Feb 20, 2025",
    provider: "Hired Provider",
    jobProviderName: "Layla Al-Sabah",
    status: "Ongoing",
    view: "View",
  },
  {
    id: 3,
    title: "Swimming Pool Deep Cleaning",
    price: "Order Price",
    jobPrice: 500,
    duration: "Duration",
    jobDuration: 2,
    orderStarted: "Order Started",
    jobStartedDate: "Jan 12, 2025",
    provider: "Hired Provider",
    jobProviderName: "Omar Al-Fahad",
    status: "Ongoing",
    view: "View",
  },
  {
    id: 4,
    title: "Electrical Wiring Fix Needed",
    price: "Order Price",
    jobPrice: 150,
    duration: "Duration",
    jobDuration: 1,
    orderStarted: "Order Started",
    jobStartedDate: "Mar 01, 2025",
    provider: "Hired Provider",
    jobProviderName: "Noor Al-Rashid",
    status: "Ongoing",
    view: "View",
  },
  {
    id: 5,
    title: "Painting & Wall Restoration",
    price: "Order Price",
    jobPrice: 400,
    duration: "Duration",
    jobDuration: 4,
    orderStarted: "Order Started",
    jobStartedDate: "Mar 10, 2025",
    provider: "Hired Provider",
    jobProviderName: "Yousef Al-Harbi",
    status: "Ongoing",
    view: "View",
  },
  {
    id: 6,
    title: "Interior Design Consultation",
    price: "Order Price",
    jobPrice: 700,
    duration: "Duration",
    jobDuration: 2,
    orderStarted: "Order Started",
    jobStartedDate: "Feb 28, 2025",
    provider: "Hired Provider",
    jobProviderName: "Salma Al-Najjar",
    status: "Ongoing",
    view: "View",
  },
  {
    id: 7,
    title: "AC Unit Repair & Maintenance",
    price: "Order Price",
    jobPrice: 180,
    duration: "Duration",
    jobDuration: 1,
    orderStarted: "Order Started",
    jobStartedDate: "Mar 06, 2025",
    provider: "Hired Provider",
    jobProviderName: "Ahmed Al-Qassim",
    status: "Ongoing",
    view: "View",
  },
  {
    id: 8,
    title: "Security Camera Installation",
    price: "Order Price",
    jobPrice: 600,
    duration: "Duration",
    jobDuration: 2,
    orderStarted: "Order Started",
    jobStartedDate: "Mar 02, 2025",
    provider: "Hired Provider",
    jobProviderName: "Fatima Al-Khalifa",
    status: "Ongoing",
    view: "View",
  },
  {
    id: 9,
    title: "Window Glass Replacement",
    price: "Order Price",
    jobPrice: 250,
    duration: "Duration",
    jobDuration: 2,
    orderStarted: "Order Started",
    jobStartedDate: "Feb 15, 2025",
    provider: "Hired Provider",
    jobProviderName: "Khalid Al-Sultan",
    status: "Ongoing",
    view: "View",
  },
  {
    id: 10,
    title: "Roof Water Proofing Required",
    price: "Order Price",
    jobPrice: 320,
    duration: "Duration",
    jobDuration: 3,
    orderStarted: "Order Started",
    jobStartedDate: "Feb 10, 2025",
    provider: "Hired Provider",
    jobProviderName: "Aisha Al-Hamdan",
    status: "Ongoing",
    view: "View",
  },
];

export const pastJobsData: JobCard[] = [
  {
    id: 1,
    title: "House Cleaning & Roofing Maintenance Needed",
    price: "Order Price",
    jobPrice: 200,
    duration: "Duration",
    jobDuration: 3,
    orderStarted: "Order Started",
    jobStartedDate: "Mar 05, 2025",
    provider: "Hired Provider",
    jobProviderName: "Saud Al-Faisal",
    status: "Completed",
    view: "View",
  },
  {
    id: 2,
    title: "Garden Landscaping Required",
    price: "Order Price",
    jobPrice: 350,
    duration: "Duration",
    jobDuration: 5,
    orderStarted: "Order Started",
    jobStartedDate: "Feb 20, 2025",
    provider: "Hired Provider",
    jobProviderName: "Layla Al-Sabah",
    status: "Completed",
    view: "View",
  },
  {
    id: 3,
    title: "Swimming Pool Deep Cleaning",
    price: "Order Price",
    jobPrice: 500,
    duration: "Duration",
    jobDuration: 2,
    orderStarted: "Order Started",
    jobStartedDate: "Jan 12, 2025",
    provider: "Hired Provider",
    jobProviderName: "Omar Al-Fahad",
    status: "Completed",
    view: "View",
  },
  {
    id: 4,
    title: "Electrical Wiring Fix Needed",
    price: "Order Price",
    jobPrice: 150,
    duration: "Duration",
    jobDuration: 1,
    orderStarted: "Order Started",
    jobStartedDate: "Mar 01, 2025",
    provider: "Hired Provider",
    jobProviderName: "Noor Al-Rashid",
    status: "Completed",
    view: "View",
  },
  {
    id: 5,
    title: "Painting & Wall Restoration",
    price: "Order Price",
    jobPrice: 400,
    duration: "Duration",
    jobDuration: 4,
    orderStarted: "Order Started",
    jobStartedDate: "Mar 10, 2025",
    provider: "Hired Provider",
    jobProviderName: "Yousef Al-Harbi",
    status: "Completed",
    view: "View",
  },
  {
    id: 6,
    title: "Interior Design Consultation",
    price: "Order Price",
    jobPrice: 700,
    duration: "Duration",
    jobDuration: 2,
    orderStarted: "Order Started",
    jobStartedDate: "Feb 28, 2025",
    provider: "Hired Provider",
    jobProviderName: "Salma Al-Najjar",
    status: "Cancelled",
    view: "View",
  },
  {
    id: 7,
    title: "AC Unit Repair & Maintenance",
    price: "Order Price",
    jobPrice: 180,
    duration: "Duration",
    jobDuration: 1,
    orderStarted: "Order Started",
    jobStartedDate: "Mar 06, 2025",
    provider: "Hired Provider",
    jobProviderName: "Ahmed Al-Qassim",
    status: "Cancelled",
    view: "View",
  },
  {
    id: 8,
    title: "Security Camera Installation",
    price: "Order Price",
    jobPrice: 600,
    duration: "Duration",
    jobDuration: 2,
    orderStarted: "Order Started",
    jobStartedDate: "Mar 02, 2025",
    provider: "Hired Provider",
    jobProviderName: "Fatima Al-Khalifa",
    status: "Cancelled",
    view: "View",
  },
  {
    id: 9,
    title: "Window Glass Replacement",
    price: "Order Price",
    jobPrice: 250,
    duration: "Duration",
    jobDuration: 2,
    orderStarted: "Order Started",
    jobStartedDate: "Feb 15, 2025",
    provider: "Hired Provider",
    jobProviderName: "Khalid Al-Sultan",
    status: "Cancelled",
    view: "View",
  },
  {
    id: 10,
    title: "Roof Water Proofing Required",
    price: "Order Price",
    jobPrice: 320,
    duration: "Duration",
    jobDuration: 3,
    orderStarted: "Order Started",
    jobStartedDate: "Feb 10, 2025",
    provider: "Hired Provider",
    jobProviderName: "Aisha Al-Hamdan",
    status: "Cancelled",
    view: "View",
  },
];

export const profileData: ProfileData[] = [
  {
    id: 1,
    img: "/service-requester-dashboard/response-rate.svg",
    label: "Response Rate",
    value: 95,
  },
  {
    id: 2,
    img: "/service-requester-dashboard/total-jobs.svg",
    label: "Total Jobs",
    value: 10,
  },
  {
    id: 3,
    img: "/service-requester-dashboard/completed-jobs.svg",
    label: "Completed Jobs",
    value: 8,
  },
  {
    id: 4,
    img: "/service-requester-dashboard/ongoing-jobs.svg",
    label: "On Going Jobs",
    value: 2,
  },
];

export const featuredFreelancer: FeaturedFreelancer[] = [
  {
    id: 1,
    icon: "/service-requester-dashboard/thunder.svg",
    label: "Highly responsive",
  },
  {
    id: 2,
    icon: "/service-requester-dashboard/stopwatch.svg",
    label: "Offers hourly rates",
  },
];

export const featuredFreelancerData: FeaturedFreelancer[] = [
  {
    id: 1,
    icon: "/service-requester-dashboard/save-icon.svg",
    label: "Save",
  },
  {
    id: 2,
    icon: "/service-requester-dashboard/share-icon.svg",
    label: "Share",
  },
];

export const skillsList: SkillsList[] = [
  {
    id: 1,
    name: "Cabinetry",
  },
  {
    id: 2,
    name: "Custom furniture making",
  },
  {
    id: 3,
    name: "Flooring installation and repair",
  },
  {
    id: 4,
    name: "Framework and structural carpentry",
  },
  {
    id: 5,
    name: "Reading blueprints and technical drawings",
  },
  {
    id: 6,
    name: "Framework and structural carpentry",
  },
];

export const packageCardData: PackageCard[] = [
  {
    id: 1,
    bgImg: "/service-requester-dashboard/cover2.svg",
    heartImg: "/service-requester-dashboard/heart.svg",
    desc: "Fast and reliable plumbing solutions at your doorstep!",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 19,
    startingFrom: "Starting from",
    value: 100,
    label: "Send job request",
  },
  {
    id: 2,
    bgImg: "/service-requester-dashboard/cover3.svg",
    heartImg: "/service-requester-dashboard/heart.svg",
    desc: "Fast and reliable plumbing solutions at your doorstep!",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 19,
    startingFrom: "Starting from",
    value: 100,
    label: "Send job request",
  },
  {
    id: 3,
    bgImg: "/service-requester-dashboard/cover2.svg",
    heartImg: "/service-requester-dashboard/heart.svg",
    desc: "Fast and reliable plumbing solutions at your doorstep!",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 19,
    startingFrom: "Starting from",
    value: 100,
    label: "Send job request",
  },
  {
    id: 4,
    bgImg: "/service-requester-dashboard/cover3.svg",
    heartImg: "/service-requester-dashboard/heart.svg",
    desc: "Fast and reliable plumbing solutions at your doorstep!",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 19,
    startingFrom: "Starting from",
    value: 100,
    label: "Send job request",
  },
  {
    id: 5,
    bgImg: "/service-requester-dashboard/cover2.svg",
    heartImg: "/service-requester-dashboard/heart.svg",
    desc: "Fast and reliable plumbing solutions at your doorstep!",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 19,
    startingFrom: "Starting from",
    value: 100,
    label: "Send job request",
  },
  {
    id: 6,
    bgImg: "/service-requester-dashboard/cover3.svg",
    heartImg: "/service-requester-dashboard/heart.svg",
    desc: "Fast and reliable plumbing solutions at your doorstep!",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 19,
    startingFrom: "Starting from",
    value: 100,
    label: "Send job request",
  },
  {
    id: 7,
    bgImg: "/service-requester-dashboard/cover2.svg",
    heartImg: "/service-requester-dashboard/heart.svg",
    desc: "Fast and reliable plumbing solutions at your doorstep!",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 19,
    startingFrom: "Starting from",
    value: 100,
    label: "Send job request",
  },
  {
    id: 8,
    bgImg: "/service-requester-dashboard/cover3.svg",
    heartImg: "/service-requester-dashboard/heart.svg",
    desc: "Fast and reliable plumbing solutions at your doorstep!",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 19,
    startingFrom: "Starting from",
    value: 100,
    label: "Send job request",
  },
];

export const portfolioData: PortfolioCard[] = [
  {
    id: 1,
    mainImg: [
      "/service-requester-dashboard/portfolio1.svg",
      "/service-requester-dashboard/portfolio2.svg",
      "/service-requester-dashboard/portfolio3.svg",
      "/service-requester-dashboard/portfolio4.svg",
      "/service-requester-dashboard/cover2.svg",
    ],
    startTime: "10 January, 2025",
    endTime: "30 February, 2025",
    projectTitle: "Plumbing & Carpentry Services",
    projectDesc:
      "Experienced in plumbing and carpentry, I provide reliable pipe installations, leak repairs, and drainage solutions, along with custom woodwork, flooring, and furniture repairs. My projects ensure durability, precision, and a professional finish for both residential and commercial spaces.",
    skills: [
      "Cleaning & Roofing Services",
      "Furniture Cleaning & Painting",
      "Pipe Installation",
      "Leak Repair",
    ],
    projectCost: 1000,
    projectDuration: 10,
    label: "SAR",
  },
  {
    id: 2,
    mainImg: [
      "/service-requester-dashboard/portfolio2.svg",
      "/service-requester-dashboard/portfolio1.svg",
      "/service-requester-dashboard/portfolio3.svg",
      "/service-requester-dashboard/portfolio4.svg",
      "/service-requester-dashboard/cover2.svg",
    ],
    startTime: "5 December, 2024",
    endTime: "10 March, 2025",
    projectTitle: "Bathroom Plumbing Renovation",
    projectDesc:
      "Complete bathroom plumbing overhaul for a residential property. Replaced old pipes, installed new fixtures, and ensured proper drainage. The project included installing a new shower system, toilet, and sink with modern fittings.",
    skills: [
      "Bathroom Renovation",
      "Pipe Replacement",
      "Fixture Installation",
      "Drainage Solutions",
    ],
    projectCost: 1500,
    projectDuration: 7,
    label: "SAR",
  },
  {
    id: 3,
    mainImg: [
      "/service-requester-dashboard/portfolio3.svg",
      "/service-requester-dashboard/portfolio1.svg",
      "/service-requester-dashboard/portfolio2.svg",
      "/service-requester-dashboard/portfolio4.svg",
      "/service-requester-dashboard/cover2.svg",
    ],
    startTime: "9 November, 2024",
    endTime: "3 April, 2025",
    projectTitle: "Commercial Pipe System Installation",
    projectDesc:
      "Designed and installed a comprehensive pipe system for a new commercial building. The project involved planning the entire water supply network, ensuring code compliance, and implementing efficient water management solutions.",
    skills: [
      "Commercial Plumbing",
      "System Design",
      "Code Compliance",
      "Water Management",
    ],
    projectCost: 3500,
    projectDuration: 14,
    label: "SAR",
  },
  {
    id: 4,
    mainImg: [
      "/service-requester-dashboard/portfolio4.svg",
      "/service-requester-dashboard/portfolio1.svg",
      "/service-requester-dashboard/portfolio2.svg",
      "/service-requester-dashboard/portfolio3.svg",
      "/service-requester-dashboard/cover2.svg",
    ],
    startTime: "15 October, 2024",
    endTime: "16 November, 2024",
    projectTitle: "Industrial Plumbing Maintenance",
    projectDesc:
      "Performed regular maintenance and repairs on an industrial plumbing system. The work included inspecting pipes, fixing leaks, replacing worn components, and ensuring the system meets safety standards.",
    skills: [
      "Industrial Plumbing",
      "Maintenance",
      "Leak Repair",
      "Safety Compliance",
    ],
    projectCost: 2000,
    projectDuration: 5,
    label: "SAR",
  },
  {
    id: 5,
    mainImg: [
      "/service-requester-dashboard/cover2.svg",
      "/service-requester-dashboard/portfolio1.svg",
      "/service-requester-dashboard/portfolio2.svg",
      "/service-requester-dashboard/portfolio3.svg",
      "/service-requester-dashboard/portfolio4.svg",
    ],
    startTime: "29 September, 2024",
    endTime: "13 February, 2025",
    projectTitle: "Emergency Leak Repair Service",
    projectDesc:
      "Provided emergency services for a major water leak in a residential building. Quickly identified the source of the leak, repaired damaged pipes, and implemented preventive measures to avoid future issues.",
    skills: [
      "Emergency Repair",
      "Leak Detection",
      "Water Damage Prevention",
      "Rapid Response",
    ],
    projectCost: 800,
    projectDuration: 2,
    label: "SAR",
  },
  {
    id: 6,
    mainImg: [
      "/service-requester-dashboard/portfolio1.svg",
      "/service-requester-dashboard/portfolio2.svg",
      "/service-requester-dashboard/portfolio3.svg",
      "/service-requester-dashboard/portfolio4.svg",
      "/service-requester-dashboard/cover2.svg",
    ],
    startTime: "12 August, 2024",
    endTime: "30 April, 2025",
    projectTitle: "Custom Kitchen Cabinetry",
    projectDesc:
      "Designed and built custom kitchen cabinets for a modern home. The project included measuring the space, selecting appropriate materials, crafting the cabinets, and installing them with precision.",
    skills: [
      "Custom Cabinetry",
      "Kitchen Renovation",
      "Woodworking",
      "Installation",
    ],
    projectCost: 4500,
    projectDuration: 12,
    label: "SAR",
  },
  {
    id: 7,
    mainImg: [
      "/service-requester-dashboard/portfolio2.svg",
      "/service-requester-dashboard/portfolio1.svg",
      "/service-requester-dashboard/portfolio3.svg",
      "/service-requester-dashboard/portfolio4.svg",
      "/service-requester-dashboard/cover2.svg",
    ],
    startTime: "7 July, 2024",
    endTime: "19 October, 2025",
    projectTitle: "Hardwood Flooring Installation",
    projectDesc:
      "Installed premium hardwood flooring throughout a residential property. The work involved preparing the subfloor, laying the hardwood planks, finishing the surface, and ensuring a seamless appearance.",
    skills: [
      "Flooring Installation",
      "Hardwood Expertise",
      "Surface Finishing",
      "Residential Work",
    ],
    projectCost: 3000,
    projectDuration: 8,
    label: "SAR",
  },
  {
    id: 8,
    mainImg: [
      "/service-requester-dashboard/portfolio3.svg",
      "/service-requester-dashboard/portfolio1.svg",
      "/service-requester-dashboard/portfolio2.svg",
      "/service-requester-dashboard/portfolio4.svg",
      "/service-requester-dashboard/cover2.svg",
    ],
    startTime: "6 June, 2024",
    endTime: "20 August, 2025",
    projectTitle: "Custom Furniture Creation",
    projectDesc:
      "Created bespoke furniture pieces for a high-end client. The project included designing unique tables, chairs, and shelving units according to the client's specifications and aesthetic preferences.",
    skills: [
      "Custom Furniture",
      "Bespoke Design",
      "Fine Woodworking",
      "Client Collaboration",
    ],
    projectCost: 5500,
    projectDuration: 15,
    label: "SAR",
  },
  {
    id: 9,
    mainImg: [
      "/service-requester-dashboard/portfolio4.svg",
      "/service-requester-dashboard/portfolio1.svg",
      "/service-requester-dashboard/portfolio2.svg",
      "/service-requester-dashboard/portfolio3.svg",
      "/service-requester-dashboard/cover2.svg",
    ],
    startTime: "4 May, 2024",
    endTime: "17 December, 2025",
    projectTitle: "Complete Home Renovation",
    projectDesc:
      "Managed a comprehensive home renovation project combining plumbing and carpentry services. The work included bathroom and kitchen updates, flooring replacement, custom built-ins, and plumbing system upgrades.",
    skills: [
      "Home Renovation",
      "Project Management",
      "Multi-trade Expertise",
      "Residential Remodeling",
    ],
    projectCost: 8000,
    projectDuration: 21,
    label: "SAR",
  },
  {
    id: 10,
    mainImg: [
      "/service-requester-dashboard/cover2.svg",
      "/service-requester-dashboard/portfolio1.svg",
      "/service-requester-dashboard/portfolio2.svg",
      "/service-requester-dashboard/portfolio3.svg",
      "/service-requester-dashboard/portfolio4.svg",
    ],
    startTime: "1 April, 2024",
    endTime: "13 February, 2025",
    projectTitle: "Office Space Remodeling",
    projectDesc:
      "Remodeled a commercial office space with both plumbing and carpentry work. The project involved creating custom partitions, installing new bathroom facilities, and designing an efficient workspace layout.",
    skills: [
      "Commercial Remodeling",
      "Office Design",
      "Workspace Optimization",
      "Multi-service Project",
    ],
    projectCost: 6500,
    projectDuration: 18,
    label: "SAR",
  },
];

export const reviewsSearchOptions = [
  "Most Recent",
  "Top Rated",
  "By Skill",
  "Project Type",
];

const generateStars = (rating: number): string[] => {
  const starPath = "/landing/popularservices/star.svg";
  return Array(rating).fill(starPath);
};

export const reviewsData: ReviewsCard[] = [
  {
    id: 1,
    img: "/service-requester-dashboard/profile3.svg",
    name: "Ahmed Al-Farsi",
    location: "Saudi Arabia",
    starImg: generateStars(1),
    rating: 1.0,
    time: "2 months ago",
    comment: "Service was okay, but could be improved in terms of timing.",
  },
  {
    id: 2,
    img: "/service-requester-dashboard/profile3.svg",
    name: "Ahmed Al-Farsi",
    location: "Saudi Arabia",
    starImg: generateStars(2),
    rating: 2.0,
    time: "3 weeks ago",
    comment:
      "Not fully satisfied. The carpentry work was decent, but delays affected the overall experience.",
  },
  {
    id: 3,
    img: "/service-requester-dashboard/profile3.svg",
    name: "Ahmed Al-Farsi",
    location: "Saudi Arabia",
    starImg: generateStars(3),
    rating: 3.0,
    time: "1 month ago",
    comment:
      "Average experience. The work was good, but customer service needs improvement.",
  },
  {
    id: 4,
    img: "/service-requester-dashboard/profile3.svg",
    name: "Ahmed Al-Farsi",
    location: "Saudi Arabia",
    starImg: generateStars(4),
    rating: 4.0,
    time: "2 weeks ago",
    comment:
      "Great job overall! Really appreciated the punctuality and attention to detail.",
  },
  {
    id: 5,
    img: "/service-requester-dashboard/profile3.svg",
    name: "Ahmed Al-Farsi",
    location: "Saudi Arabia",
    starImg: generateStars(5),
    rating: 5.0,
    time: "1 week ago",
    comment:
      "Outstanding service! Extremely professional and high-quality workmanship.",
  },
];

export const jobServiceDescriptionData: JobServiceDescription[] = [
  {
    id: 1,
    icon: "/service-requester-dashboard/check-icon.svg",
    desc: "Read and interpret blueprints, schematics, and technical drawings to plan plumbing layouts.",
  },
  {
    id: 2,
    icon: "/service-requester-dashboard/check-icon.svg",
    desc: "Install, repair, and maintain plumbing systems, including pipes, fixtures, and fittings in bathrooms and kitchens.",
  },
  {
    id: 3,
    icon: "/service-requester-dashboard/check-icon.svg",
    desc: "Connect water supply lines, drainage systems, and gas lines according to building codes and safety regulations.",
  },
];

export const jobRequirementsData: JobRequirements[] = [
  {
    id: 1,
    icon: "/service-requester-dashboard/experience.svg",
    label: "Experience",
    desc: "Senior Level",
  },
  {
    id: 2,
    icon: "/service-requester-dashboard/languages.svg",
    label: "Languages",
    desc: "Arabic, English, Urdu",
  },
  {
    id: 3,
    icon: "/service-requester-dashboard/calendar.svg",
    label: "Project Duration",
    desc: "3 days",
  },
];

export const jobSupportData: JobSupport[] = [
  {
    id: 1,
    icon: "/service-requester-dashboard/question.svg",
    label: "FAQ's",
    desc: "Find needed answer.",
    href: "/service-requester-dashboard?view=faqs",
    separator: "w-full h-[0.5px] bg-[#0000004D] mt-[4px]",
  },
  {
    id: 2,
    icon: "/service-requester-dashboard/globe.svg",
    label: "Resolution Center",
    desc: "Resolve order issues.",
    href: "/resolution-center",
  },
];

export const requesterDisputesData: RequesterDisputes[] = [
  {
    id: 1,
    refNumber: "11564",
    employerName: "Haider Ali",
    date: "2/5/2025",
    amount: 113,
    currency: "SAR",
    status: "Disputed",
  },
  {
    id: 2,
    refNumber: "11572",
    employerName: "Farooq Khan",
    date: "13/4/2025",
    amount: 324,
    currency: "SAR",
    status: "Disputed",
  },
  {
    id: 3,
    refNumber: "11529",
    employerName: "Haider Ali",
    date: "13/4/2025",
    amount: 214,
    currency: "SAR",
    status: "Disputed",
  },
  {
    id: 4,
    refNumber: "11292",
    employerName: "Farooq Khan",
    date: "13/4/2025",
    amount: 121,
    currency: "SAR",
    status: "Disputed",
  },
  {
    id: 5,
    refNumber: "13810",
    employerName: "Haider Ali",
    date: "13/4/2025",
    amount: 140,
    currency: "SAR",
    status: "Disputed",
  },
  {
    id: 6,
    refNumber: "11823",
    employerName: "Sana Mir",
    date: "10/4/2025",
    amount: 190,
    currency: "SAR",
    status: "Disputed",
  },
  {
    id: 7,
    refNumber: "11756",
    employerName: "Ahmed Raza",
    date: "11/4/2025",
    amount: 256,
    currency: "SAR",
    status: "Disputed",
  },
  {
    id: 8,
    refNumber: "11478",
    employerName: "Zara Sheikh",
    date: "9/4/2025",
    amount: 330,
    currency: "SAR",
    status: "Disputed",
  },
  {
    id: 9,
    refNumber: "11634",
    employerName: "Imran Malik",
    date: "12/4/2025",
    amount: 275,
    currency: "SAR",
    status: "Disputed",
  },
  {
    id: 10,
    refNumber: "11901",
    employerName: "Ayesha Khan",
    date: "8/4/2025",
    amount: 145,
    currency: "SAR",
    status: "Disputed",
  },
  {
    id: 11,
    refNumber: "11390",
    employerName: "Usman Tariq",
    date: "7/4/2025",
    amount: 198,
    currency: "SAR",
    status: "Disputed",
  },
  {
    id: 12,
    refNumber: "11127",
    employerName: "Rabia Yousaf",
    date: "6/4/2025",
    amount: 220,
    currency: "SAR",
    status: "Disputed",
  },
  {
    id: 13,
    refNumber: "12003",
    employerName: "Noman Shah",
    date: "5/4/2025",
    amount: 310,
    currency: "SAR",
    status: "Disputed",
  },
  {
    id: 14,
    refNumber: "12114",
    employerName: "Laiba Noor",
    date: "4/4/2025",
    amount: 175,
    currency: "SAR",
    status: "Disputed",
  },
  {
    id: 15,
    refNumber: "12225",
    employerName: "Bilal Ansari",
    date: "3/4/2025",
    amount: 200,
    currency: "SAR",
    status: "Disputed",
  },
];

export const accountDeactivationData = [
  {
    id: 1,
    desc: "Your profile and packages won’t be shown on Ednuvo anymore.",
  },
  {
    id: 2,
    desc: "Active orders will be cancelled.",
  },
  {
    id: 3,
    desc: "You won’t be able to re-activate your packages.",
  },
];

export const requesterFaqData: FAQ[] = [
  {
    id: 1,
    title: "How do I post a new service request?",
    desc: "To post a service request, simply log in to your account, go to the 'Post a Job' section, select the category of service (e.g., plumbing, electrical), fill in the job details, and submit. Service providers in your area will be notified instantly.",
  },
  {
    id: 2,
    title: "Can I contact a service provider before hiring them?",
    desc: "Yes, you can chat with service providers through our in-app messaging system once they express interest in your job post. This helps you clarify job details before making a hiring decision.",
  },
  {
    id: 3,
    title: "How do I know if a service provider is qualified?",
    desc: "All service providers undergo a verification process, which includes skill assessments and identity verification. You can also view their ratings, reviews, and past work on their profiles before hiring.",
  },
  {
    id: 4,
    title: "What should I do if a service provider doesn’t show up?",
    desc: "If a provider fails to show up or communicate, please report the issue through the 'Help & Support' section. Our support team will investigate and assist you with finding a replacement as soon as possible.",
  },
  {
    id: 5,
    title: "How is payment handled for services?",
    desc: "Payment is handled securely through our platform. You only pay once the job is completed and you're satisfied with the service. For larger jobs, milestone payments can also be arranged.",
  },
  {
    id: 6,
    title: "Can I cancel a service request after posting?",
    desc: "Yes, you can cancel a request at any time before the job is accepted. If a provider has already been hired, please communicate with them directly or contact support to help with the cancellation process.",
  },
];
