import {
  AnalyticsCard,
  ExpertsCard,
  FeaturedFreelancer,
  JobCard,
  JobServiceDescription,
  MenuSection,
  PackageCard,
  ProfileData,
  ReviewsCard,
  SkillsList,
  UserCard,
} from "@/interfaces/Service-Requester-Dashboard";

export const menuLinks: MenuSection[] = [
  {
    id: 1,
    title: "General",
    links: [
      {
        id: 1,
        icon: "/service-requester-dashboard/dashboard.svg",
        icon2: "/service-requester-dashboard/dashboard2.svg",
        label: "Dashboard",
        url: "?view=dashboard",
      },
      {
        id: 2,
        icon: "/service-requester-dashboard/jobs.svg",
        icon2: "/service-requester-dashboard/jobs2.svg",
        label: "Jobs",
        url: "?view=jobs",
      },
      {
        id: 3,
        icon: "/service-requester-dashboard/disputes.svg",
        icon2: "/service-requester-dashboard/disputes2.svg",
        label: "Disputes",
        url: "?view=disputes",
      },
      {
        id: 4,
        icon: "/service-requester-dashboard/messages.svg",
        icon2: "/service-requester-dashboard/messages2.svg",
        label: "Messages",
        url: "?view=messages",
      },
    ],
  },
  {
    id: 2,
    title: "Tools",
    links: [
      {
        id: 1,
        icon: "/service-requester-dashboard/payment.svg",
        icon2: "/service-requester-dashboard/payment2.svg",
        label: "Payment",
        url: "#",
      },
      {
        id: 2,
        icon: "/service-requester-dashboard/setting.svg",
        icon2: "/service-requester-dashboard/setting2.svg",
        label: "Setting",
        url: "#",
      },
      {
        id: 3,
        icon: "/service-requester-dashboard/faq.svg",
        icon2: "/service-requester-dashboard/faq2.svg",
        label: "FAQs",
        url: "#",
      },
      {
        id: 4,
        icon: "/service-requester-dashboard/logout.svg",
        icon2: "/service-requester-dashboard/logout2.svg",
        label: "Logout",
        url: "#",
      },
    ],
  },
];

export const expertsCardData: ExpertsCard[] = [
  {
    id: 1,
    profileImg: "/service-requester-dashboard/profile.svg",
    name: "Saud Al-Faisal",
    occpation: "Expert Plumber",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 20,
    desc: "Reliable plumbing services with quick response time and high-quality repairs.",
    budgetImg: "/service-requester-dashboard/budget.svg",
    budget: "Budget",
    budgetValue: 100,
    locationImg: "/service-requester-dashboard/location.svg",
    location: "Location",
    locationVenue: "Riyadh, Saudi Arabia",
    skills: [
      { id: 1, label: "Pipe Repair" },
      { id: 2, label: "Leak fixing" },
      { id: 3, label: "Drain Cleaning" },
      { id: 4, label: "Bathroom Installations" },
      { id: 5, label: "Water Heater Installation" },
      { id: 6, label: "Fixture Replacement" },
      { id: 7, label: "Sewer Line Services" },
      { id: 8, label: "Emergency Plumbing" },
    ],
    button: "Send Job Request",
  },
  {
    id: 2,
    profileImg: "/service-requester-dashboard/profile2.svg",
    name: "Ahmed Bin Zayed",
    occpation: "Expert Plumber",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 20,
    desc: "Reliable plumbing services with quick response time and high-quality repairs.",
    budgetImg: "/service-requester-dashboard/budget.svg",
    budget: "Budget",
    budgetValue: 100,
    locationImg: "/service-requester-dashboard/location.svg",
    location: "Location",
    locationVenue: "Riyadh, Saudi Arabia",
    skills: [
      { id: 1, label: "Pipe Repair" },
      { id: 2, label: "Leak fixing" },
      { id: 3, label: "Drain Cleaning" },
      { id: 4, label: "Bathroom Installations" },
      { id: 5, label: "Water Heater Installation" },
      { id: 6, label: "Fixture Replacement" },
      { id: 7, label: "Sewer Line Services" },
      { id: 8, label: "Emergency Plumbing" },
    ],
    button: "Send Job Request",
  },
  {
    id: 3,
    profileImg: "/service-requester-dashboard/profile2.svg",
    name: "Fatima Al-Nasser",
    occpation: "Expert Plumber",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 20,
    desc: "Reliable plumbing services with quick response time and high-quality repairs.",
    budgetImg: "/service-requester-dashboard/budget.svg",
    budget: "Budget",
    budgetValue: 100,
    locationImg: "/service-requester-dashboard/location.svg",
    location: "Location",
    locationVenue: "Riyadh, Saudi Arabia",
    skills: [
      { id: 1, label: "Pipe Repair" },
      { id: 2, label: "Leak fixing" },
      { id: 3, label: "Drain Cleaning" },
      { id: 4, label: "Bathroom Installations" },
      { id: 5, label: "Water Heater Installation" },
      { id: 6, label: "Fixture Replacement" },
      { id: 7, label: "Sewer Line Services" },
      { id: 8, label: "Emergency Plumbing" },
    ],
    button: "Send Job Request",
  },
  {
    id: 4,
    profileImg: "/service-requester-dashboard/profile2.svg",
    name: "Omar Al-Khalid",
    occpation: "Expert Plumber",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 20,
    desc: "Reliable plumbing services with quick response time and high-quality repairs.",
    budgetImg: "/service-requester-dashboard/budget.svg",
    budget: "Budget",
    budgetValue: 100,
    locationImg: "/service-requester-dashboard/location.svg",
    location: "Location",
    locationVenue: "Riyadh, Saudi Arabia",
    skills: [
      { id: 1, label: "Pipe Repair" },
      { id: 2, label: "Leak fixing" },
      { id: 3, label: "Drain Cleaning" },
      { id: 4, label: "Bathroom Installations" },
      { id: 5, label: "Water Heater Installation" },
      { id: 6, label: "Fixture Replacement" },
      { id: 7, label: "Sewer Line Services" },
      { id: 8, label: "Emergency Plumbing" },
    ],
    button: "Send Job Request",
  },
  {
    id: 5,
    profileImg: "/service-requester-dashboard/profile2.svg",
    name: "Laila Al-Farouq",
    occpation: "Expert Plumber",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 20,
    desc: "Reliable plumbing services with quick response time and high-quality repairs.",
    budgetImg: "/service-requester-dashboard/budget.svg",
    budget: "Budget",
    budgetValue: 100,
    locationImg: "/service-requester-dashboard/location.svg",
    location: "Location",
    locationVenue: "Riyadh, Saudi Arabia",
    skills: [
      { id: 1, label: "Pipe Repair" },
      { id: 2, label: "Leak fixing" },
      { id: 3, label: "Drain Cleaning" },
      { id: 4, label: "Bathroom Installations" },
      { id: 5, label: "Water Heater Installation" },
      { id: 6, label: "Fixture Replacement" },
      { id: 7, label: "Sewer Line Services" },
      { id: 8, label: "Emergency Plumbing" },
    ],
    button: "Send Job Request",
  },
  {
    id: 6,
    profileImg: "/service-requester-dashboard/profile2.svg",
    name: "Hassan Al-Mutairi",
    occpation: "Expert Plumber",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 20,
    desc: "Reliable plumbing services with quick response time and high-quality repairs.",
    budgetImg: "/service-requester-dashboard/budget.svg",
    budget: "Budget",
    budgetValue: 100,
    locationImg: "/service-requester-dashboard/location.svg",
    location: "Location",
    locationVenue: "Riyadh, Saudi Arabia",
    skills: [
      { id: 1, label: "Pipe Repair" },
      { id: 2, label: "Leak fixing" },
      { id: 3, label: "Drain Cleaning" },
      { id: 4, label: "Bathroom Installations" },
      { id: 5, label: "Water Heater Installation" },
      { id: 6, label: "Fixture Replacement" },
      { id: 7, label: "Sewer Line Services" },
      { id: 8, label: "Emergency Plumbing" },
    ],
    button: "Send Job Request",
  },
];

export const searchOptions = ["Rating", "Reviews", "Price", "Newest", "Oldest"];

export const analyticsCardData: AnalyticsCard[] = [
  {
    id: 1,
    label: "Posted Jobs",
    value: 12,
  },
  {
    id: 2,
    label: "On Going Contracts",
    value: 7,
  },
  {
    id: 3,
    label: "Order Completion Rate",
    value: 99,
    unit: "%",
  },
  {
    id: 4,
    label: "Total Spendings",
    value: 500,
    unit: "SAR",
  },
];

export const userCardData: UserCard[] = [
  {
    id: 1,
    bgImg: "/service-requester-dashboard/cover.svg",
    heartImg: "/service-requester-dashboard/heart.svg",
    profileImg: "/service-requester-dashboard/profile.svg",
    status: "online",
    name: "Saud Al-Faisal",
    desc: "Fast and reliable plumbing solutions at your doorstep!",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 19,
    startingFrom: "Starting from",
    value: 100,
  },
  {
    id: 2,
    bgImg: "/service-requester-dashboard/cover.svg",
    heartImg: "/service-requester-dashboard/heart.svg",
    profileImg: "/service-requester-dashboard/profile.svg",
    status: "offline",
    name: "Saud Al-Faisal",
    desc: "Fast and reliable plumbing solutions at your doorstep!",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 19,
    startingFrom: "Starting from",
    value: 100,
  },
  {
    id: 3,
    bgImg: "/service-requester-dashboard/cover.svg",
    heartImg: "/service-requester-dashboard/heart.svg",
    profileImg: "/service-requester-dashboard/profile.svg",
    status: "online",
    name: "Saud Al-Faisal",
    desc: "Fast and reliable plumbing solutions at your doorstep!",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 19,
    startingFrom: "Starting from",
    value: 100,
  },
  {
    id: 4,
    bgImg: "/service-requester-dashboard/cover.svg",
    heartImg: "/service-requester-dashboard/heart.svg",
    profileImg: "/service-requester-dashboard/profile.svg",
    status: "offline",
    name: "Saud Al-Faisal",
    desc: "Fast and reliable plumbing solutions at your doorstep!",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 19,
    startingFrom: "Starting from",
    value: 100,
  },
  {
    id: 5,
    bgImg: "/service-requester-dashboard/cover.svg",
    heartImg: "/service-requester-dashboard/heart.svg",
    profileImg: "/service-requester-dashboard/profile.svg",
    status: "online",
    name: "Saud Al-Faisal",
    desc: "Fast and reliable plumbing solutions at your doorstep!",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 19,
    startingFrom: "Starting from",
    value: 100,
  },
  {
    id: 6,
    bgImg: "/service-requester-dashboard/cover.svg",
    heartImg: "/service-requester-dashboard/heart.svg",
    profileImg: "/service-requester-dashboard/profile.svg",
    status: "offline",
    name: "Saud Al-Faisal",
    desc: "Fast and reliable plumbing solutions at your doorstep!",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 19,
    startingFrom: "Starting from",
    value: 100,
  },
  {
    id: 7,
    bgImg: "/service-requester-dashboard/cover.svg",
    heartImg: "/service-requester-dashboard/heart.svg",
    profileImg: "/service-requester-dashboard/profile.svg",
    status: "online",
    name: "Saud Al-Faisal",
    desc: "Fast and reliable plumbing solutions at your doorstep!",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 19,
    startingFrom: "Starting from",
    value: 100,
  },
  {
    id: 8,
    bgImg: "/service-requester-dashboard/cover.svg",
    heartImg: "/service-requester-dashboard/heart.svg",
    profileImg: "/service-requester-dashboard/profile.svg",
    status: "offline",
    name: "Saud Al-Faisal",
    desc: "Fast and reliable plumbing solutions at your doorstep!",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 19,
    startingFrom: "Starting from",
    value: 100,
  },
];

export const activeJobsData: JobCard[] = [
  {
    id: 1,
    title: "House Cleaning & Roofing Maintenance Needed",
    price: "Order Price",
    jobPrice: 200,
    duration: "Duration",
    jobDuration: 3,
    orderStarted: "Order Started",
    jobStartedDate: "Mar 05, 2025",
    provider: "Hired Provider",
    jobProviderName: "Saud Al-Faisal",
    status: "Ongoing",
    view: "View",
  },
  {
    id: 2,
    title: "Garden Landscaping Required",
    price: "Order Price",
    jobPrice: 350,
    duration: "Duration",
    jobDuration: 5,
    orderStarted: "Order Started",
    jobStartedDate: "Feb 20, 2025",
    provider: "Hired Provider",
    jobProviderName: "Layla Al-Sabah",
    status: "Completed",
    view: "View",
  },
  {
    id: 3,
    title: "Swimming Pool Deep Cleaning",
    price: "Order Price",
    jobPrice: 500,
    duration: "Duration",
    jobDuration: 2,
    orderStarted: "Order Started",
    jobStartedDate: "Jan 12, 2025",
    provider: "Hired Provider",
    jobProviderName: "Omar Al-Fahad",
    status: "Pending",
    view: "View",
  },
  {
    id: 4,
    title: "Electrical Wiring Fix Needed",
    price: "Order Price",
    jobPrice: 150,
    duration: "Duration",
    jobDuration: 1,
    orderStarted: "Order Started",
    jobStartedDate: "Mar 01, 2025",
    provider: "Hired Provider",
    jobProviderName: "Noor Al-Rashid",
    status: "Cancelled",
    view: "View",
  },
  {
    id: 5,
    title: "Painting & Wall Restoration",
    price: "Order Price",
    jobPrice: 400,
    duration: "Duration",
    jobDuration: 4,
    orderStarted: "Order Started",
    jobStartedDate: "Mar 10, 2025",
    provider: "Hired Provider",
    jobProviderName: "Yousef Al-Harbi",
    status: "Ongoing",
    view: "View",
  },
  {
    id: 6,
    title: "Interior Design Consultation",
    price: "Order Price",
    jobPrice: 700,
    duration: "Duration",
    jobDuration: 2,
    orderStarted: "Order Started",
    jobStartedDate: "Feb 28, 2025",
    provider: "Hired Provider",
    jobProviderName: "Salma Al-Najjar",
    status: "Completed",
    view: "View",
  },
  {
    id: 7,
    title: "AC Unit Repair & Maintenance",
    price: "Order Price",
    jobPrice: 180,
    duration: "Duration",
    jobDuration: 1,
    orderStarted: "Order Started",
    jobStartedDate: "Mar 06, 2025",
    provider: "Hired Provider",
    jobProviderName: "Ahmed Al-Qassim",
    status: "Ongoing",
    view: "View",
  },
  {
    id: 8,
    title: "Security Camera Installation",
    price: "Order Price",
    jobPrice: 600,
    duration: "Duration",
    jobDuration: 2,
    orderStarted: "Order Started",
    jobStartedDate: "Mar 02, 2025",
    provider: "Hired Provider",
    jobProviderName: "Fatima Al-Khalifa",
    status: "Pending",
    view: "View",
  },
  {
    id: 9,
    title: "Window Glass Replacement",
    price: "Order Price",
    jobPrice: 250,
    duration: "Duration",
    jobDuration: 2,
    orderStarted: "Order Started",
    jobStartedDate: "Feb 15, 2025",
    provider: "Hired Provider",
    jobProviderName: "Khalid Al-Sultan",
    status: "Completed",
    view: "View",
  },
  {
    id: 10,
    title: "Roof Water Proofing Required",
    price: "Order Price",
    jobPrice: 320,
    duration: "Duration",
    jobDuration: 3,
    orderStarted: "Order Started",
    jobStartedDate: "Feb 10, 2025",
    provider: "Hired Provider",
    jobProviderName: "Aisha Al-Hamdan",
    status: "Ongoing",
    view: "View",
  },
];

export const pastJobsData: JobCard[] = [
  {
    id: 1,
    title: "House Cleaning & Roofing Maintenance Needed",
    price: "Order Price",
    jobPrice: 200,
    duration: "Duration",
    jobDuration: 3,
    orderStarted: "Order Started",
    jobStartedDate: "Mar 05, 2025",
    provider: "Hired Provider",
    jobProviderName: "Saud Al-Faisal",
    status: "Completed",
    view: "View",
  },
  {
    id: 2,
    title: "Garden Landscaping Required",
    price: "Order Price",
    jobPrice: 350,
    duration: "Duration",
    jobDuration: 5,
    orderStarted: "Order Started",
    jobStartedDate: "Feb 20, 2025",
    provider: "Hired Provider",
    jobProviderName: "Layla Al-Sabah",
    status: "Completed",
    view: "View",
  },
  {
    id: 3,
    title: "Swimming Pool Deep Cleaning",
    price: "Order Price",
    jobPrice: 500,
    duration: "Duration",
    jobDuration: 2,
    orderStarted: "Order Started",
    jobStartedDate: "Jan 12, 2025",
    provider: "Hired Provider",
    jobProviderName: "Omar Al-Fahad",
    status: "Completed",
    view: "View",
  },
  {
    id: 4,
    title: "Electrical Wiring Fix Needed",
    price: "Order Price",
    jobPrice: 150,
    duration: "Duration",
    jobDuration: 1,
    orderStarted: "Order Started",
    jobStartedDate: "Mar 01, 2025",
    provider: "Hired Provider",
    jobProviderName: "Noor Al-Rashid",
    status: "Completed",
    view: "View",
  },
  {
    id: 5,
    title: "Painting & Wall Restoration",
    price: "Order Price",
    jobPrice: 400,
    duration: "Duration",
    jobDuration: 4,
    orderStarted: "Order Started",
    jobStartedDate: "Mar 10, 2025",
    provider: "Hired Provider",
    jobProviderName: "Yousef Al-Harbi",
    status: "Completed",
    view: "View",
  },
  {
    id: 6,
    title: "Interior Design Consultation",
    price: "Order Price",
    jobPrice: 700,
    duration: "Duration",
    jobDuration: 2,
    orderStarted: "Order Started",
    jobStartedDate: "Feb 28, 2025",
    provider: "Hired Provider",
    jobProviderName: "Salma Al-Najjar",
    status: "Completed",
    view: "View",
  },
  {
    id: 7,
    title: "AC Unit Repair & Maintenance",
    price: "Order Price",
    jobPrice: 180,
    duration: "Duration",
    jobDuration: 1,
    orderStarted: "Order Started",
    jobStartedDate: "Mar 06, 2025",
    provider: "Hired Provider",
    jobProviderName: "Ahmed Al-Qassim",
    status: "Completed",
    view: "View",
  },
  {
    id: 8,
    title: "Security Camera Installation",
    price: "Order Price",
    jobPrice: 600,
    duration: "Duration",
    jobDuration: 2,
    orderStarted: "Order Started",
    jobStartedDate: "Mar 02, 2025",
    provider: "Hired Provider",
    jobProviderName: "Fatima Al-Khalifa",
    status: "Completed",
    view: "View",
  },
  {
    id: 9,
    title: "Window Glass Replacement",
    price: "Order Price",
    jobPrice: 250,
    duration: "Duration",
    jobDuration: 2,
    orderStarted: "Order Started",
    jobStartedDate: "Feb 15, 2025",
    provider: "Hired Provider",
    jobProviderName: "Khalid Al-Sultan",
    status: "Completed",
    view: "View",
  },
  {
    id: 10,
    title: "Roof Water Proofing Required",
    price: "Order Price",
    jobPrice: 320,
    duration: "Duration",
    jobDuration: 3,
    orderStarted: "Order Started",
    jobStartedDate: "Feb 10, 2025",
    provider: "Hired Provider",
    jobProviderName: "Aisha Al-Hamdan",
    status: "Completed",
    view: "View",
  },
];

export const profileData: ProfileData[] = [
  {
    id: 1,
    img: "/service-requester-dashboard/response-rate.svg",
    label: "Response Rate",
    value: 95,
  },
  {
    id: 2,
    img: "/service-requester-dashboard/total-jobs.svg",
    label: "Total Jobs",
    value: 10,
  },
  {
    id: 3,
    img: "/service-requester-dashboard/completed-jobs.svg",
    label: "Completed Jobs",
    value: 8,
  },
  {
    id: 4,
    img: "/service-requester-dashboard/ongoing-jobs.svg",
    label: "On Going Jobs",
    value: 2,
  },
];

export const featuredFreelancer: FeaturedFreelancer[] = [
  {
    id: 1,
    icon: "/service-requester-dashboard/thunder.svg",
    label: "Highly responsive",
  },
  {
    id: 2,
    icon: "/service-requester-dashboard/stopwatch.svg",
    label: "Offers hourly rates",
  },
];

export const featuredFreelancerData: FeaturedFreelancer[] = [
  {
    id: 1,
    icon: "/service-requester-dashboard/save.svg",
    label: "Save",
  },
  {
    id: 2,
    icon: "/service-requester-dashboard/share.svg",
    label: "Share",
  },
];

export const skillsList: SkillsList[] = [
  {
    id: 1,
    name: "Cabinetry",
  },
  {
    id: 2,
    name: "Custom furniture making",
  },
  {
    id: 3,
    name: "Flooring installation and repair",
  },
  {
    id: 4,
    name: "Framework and structural carpentry",
  },
  {
    id: 5,
    name: "Reading blueprints and technical drawings",
  },
  {
    id: 6,
    name: "Framework and structural carpentry",
  },
];

export const packageCardData: PackageCard[] = [
  {
    id: 1,
    bgImg: "/service-requester-dashboard/cover2.svg",
    heartImg: "/service-requester-dashboard/heart.svg",
    desc: "Fast and reliable plumbing solutions at your doorstep!",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 19,
    startingFrom: "Starting from",
    value: 100,
    label: "Send job request",
  },
  {
    id: 2,
    bgImg: "/service-requester-dashboard/cover3.svg",
    heartImg: "/service-requester-dashboard/heart.svg",
    desc: "Fast and reliable plumbing solutions at your doorstep!",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 19,
    startingFrom: "Starting from",
    value: 100,
    label: "Send job request",
  },
  {
    id: 3,
    bgImg: "/service-requester-dashboard/cover2.svg",
    heartImg: "/service-requester-dashboard/heart.svg",
    desc: "Fast and reliable plumbing solutions at your doorstep!",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 19,
    startingFrom: "Starting from",
    value: 100,
    label: "Send job request",
  },
  {
    id: 4,
    bgImg: "/service-requester-dashboard/cover3.svg",
    heartImg: "/service-requester-dashboard/heart.svg",
    desc: "Fast and reliable plumbing solutions at your doorstep!",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 19,
    startingFrom: "Starting from",
    value: 100,
    label: "Send job request",
  },
];

export const reviewsSearchOptions = [
  "Most Recent",
  "Top Rated",
  "By Skill",
  "Project Type",
];

const generateStars = (rating: number): string[] => {
  const starPath = "/landing/popularservices/star.svg";
  return Array(rating).fill(starPath);
};

export const reviewsData: ReviewsCard[] = [
  {
    id: 1,
    img: "/service-requester-dashboard/profile3.svg",
    name: "Ahmed Al-Farsi",
    location: "Saudi Arabia",
    starImg: generateStars(1),
    rating: 1.0,
    time: "2 months ago",
    comment: "Service was okay, but could be improved in terms of timing.",
  },
  {
    id: 2,
    img: "/service-requester-dashboard/profile3.svg",
    name: "Ahmed Al-Farsi",
    location: "Saudi Arabia",
    starImg: generateStars(2),
    rating: 2.0,
    time: "3 weeks ago",
    comment:
      "Not fully satisfied. The carpentry work was decent, but delays affected the overall experience.",
  },
  {
    id: 3,
    img: "/service-requester-dashboard/profile3.svg",
    name: "Ahmed Al-Farsi",
    location: "Saudi Arabia",
    starImg: generateStars(3),
    rating: 3.0,
    time: "1 month ago",
    comment:
      "Average experience. The work was good, but customer service needs improvement.",
  },
  {
    id: 4,
    img: "/service-requester-dashboard/profile3.svg",
    name: "Ahmed Al-Farsi",
    location: "Saudi Arabia",
    starImg: generateStars(4),
    rating: 4.0,
    time: "2 weeks ago",
    comment:
      "Great job overall! Really appreciated the punctuality and attention to detail.",
  },
  {
    id: 5,
    img: "/service-requester-dashboard/profile3.svg",
    name: "Ahmed Al-Farsi",
    location: "Saudi Arabia",
    starImg: generateStars(5),
    rating: 5.0,
    time: "1 week ago",
    comment:
      "Outstanding service! Extremely professional and high-quality workmanship.",
  },
];

export const jobServiceDescriptionData: JobServiceDescription[] = [
  {
    id: 1,
    icon: "/service-requester-dashboard/check-icon.svg",
    desc: "Read and interpret blueprints, schematics, and technical drawings to plan plumbing layouts.",
  },
  {
    id: 2,
    icon: "/service-requester-dashboard/check-icon.svg",
    desc: "Install, repair, and maintain plumbing systems, including pipes, fixtures, and fittings in bathrooms and kitchens.",
  },
  {
    id: 3,
    icon: "/service-requester-dashboard/check-icon.svg",
    desc: "Connect water supply lines, drainage systems, and gas lines according to building codes and safety regulations.",
  },
];
