import {
  ExpertsCard,
  MenuSection,
} from "@/interfaces/Service-Requester-Dashboard";

export const menuLinks: MenuSection[] = [
  {
    id: 1,
    title: "General",
    links: [
      {
        id: 1,
        icon: "/service-requester-dashboard/dashboard.svg",
        icon2: "/service-requester-dashboard/dashboard2.svg",
        label: "Dashboard",
        url: "?view=dashboard",
      },
      {
        id: 2,
        icon: "/service-requester-dashboard/jobs.svg",
        icon2: "/service-requester-dashboard/jobs2.svg",
        label: "Jobs",
        url: "?view=jobs",
      },
      {
        id: 3,
        icon: "/service-requester-dashboard/disputes.svg",
        icon2: "/service-requester-dashboard/disputes2.svg",
        label: "Disputes",
        url: "?view=disputes",
      },
      {
        id: 4,
        icon: "/service-requester-dashboard/messages.svg",
        icon2: "/service-requester-dashboard/messages2.svg",
        label: "Messages",
        url: "?view=messages",
      },
    ],
  },
  {
    id: 2,
    title: "Tools",
    links: [
      {
        id: 1,
        icon: "/service-requester-dashboard/payment.svg",
        icon2: "/service-requester-dashboard/payment2.svg",
        label: "Payment",
        url: "#",
      },
      {
        id: 2,
        icon: "/service-requester-dashboard/setting.svg",
        icon2: "/service-requester-dashboard/setting2.svg",
        label: "Setting",
        url: "#",
      },
      {
        id: 3,
        icon: "/service-requester-dashboard/faq.svg",
        icon2: "/service-requester-dashboard/faq2.svg",
        label: "FAQs",
        url: "#",
      },
      {
        id: 4,
        icon: "/service-requester-dashboard/logout.svg",
        icon2: "/service-requester-dashboard/logout2.svg",
        label: "Logout",
        url: "#",
      },
    ],
  },
];

export const expertsCardData: ExpertsCard[] = [
  {
    id: 1,
    profileImg: "/service-requester-dashboard/profile.svg",
    name: "Saud Al-Faisal",
    occpation: "Expert Plumber",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 20,
    desc: "Reliable plumbing services with quick response time and high-quality repairs.",
    budgetImg: "/service-requester-dashboard/budget.svg",
    budget: "Budget",
    budgetValue: 100,
    locationImg: "/service-requester-dashboard/location.svg",
    location: "Location",
    locationVenue: "Riyadh, Saudi Arabia",
    skills: [
      { id: 1, label: "Pipe Repair" },
      { id: 2, label: "Leak fixing" },
      { id: 3, label: "Drain Cleaning" },
      { id: 4, label: "Bathroom Installations" },
      { id: 5, label: "Water Heater Installation" },
      { id: 6, label: "Fixture Replacement" },
      { id: 7, label: "Sewer Line Services" },
      { id: 8, label: "Emergency Plumbing" },
    ],
    button: "Send Job Request",
  },
  {
    id: 2,
    profileImg: "/service-requester-dashboard/profile2.svg",
    name: "Ahmed Bin Zayed",
    occpation: "Expert Plumber",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 20,
    desc: "Reliable plumbing services with quick response time and high-quality repairs.",
    budgetImg: "/service-requester-dashboard/budget.svg",
    budget: "Budget",
    budgetValue: 100,
    locationImg: "/service-requester-dashboard/location.svg",
    location: "Location",
    locationVenue: "Riyadh, Saudi Arabia",
    skills: [
      { id: 1, label: "Pipe Repair" },
      { id: 2, label: "Leak fixing" },
      { id: 3, label: "Drain Cleaning" },
      { id: 4, label: "Bathroom Installations" },
      { id: 5, label: "Water Heater Installation" },
      { id: 6, label: "Fixture Replacement" },
      { id: 7, label: "Sewer Line Services" },
      { id: 8, label: "Emergency Plumbing" },
    ],
    button: "Send Job Request",
  },
  {
    id: 3,
    profileImg: "/service-requester-dashboard/profile2.svg",
    name: "Fatima Al-Nasser",
    occpation: "Expert Plumber",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 20,
    desc: "Reliable plumbing services with quick response time and high-quality repairs.",
    budgetImg: "/service-requester-dashboard/budget.svg",
    budget: "Budget",
    budgetValue: 100,
    locationImg: "/service-requester-dashboard/location.svg",
    location: "Location",
    locationVenue: "Riyadh, Saudi Arabia",
    skills: [
      { id: 1, label: "Pipe Repair" },
      { id: 2, label: "Leak fixing" },
      { id: 3, label: "Drain Cleaning" },
      { id: 4, label: "Bathroom Installations" },
      { id: 5, label: "Water Heater Installation" },
      { id: 6, label: "Fixture Replacement" },
      { id: 7, label: "Sewer Line Services" },
      { id: 8, label: "Emergency Plumbing" },
    ],
    button: "Send Job Request",
  },
  {
    id: 4,
    profileImg: "/service-requester-dashboard/profile2.svg",
    name: "Omar Al-Khalid",
    occpation: "Expert Plumber",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 20,
    desc: "Reliable plumbing services with quick response time and high-quality repairs.",
    budgetImg: "/service-requester-dashboard/budget.svg",
    budget: "Budget",
    budgetValue: 100,
    locationImg: "/service-requester-dashboard/location.svg",
    location: "Location",
    locationVenue: "Riyadh, Saudi Arabia",
    skills: [
      { id: 1, label: "Pipe Repair" },
      { id: 2, label: "Leak fixing" },
      { id: 3, label: "Drain Cleaning" },
      { id: 4, label: "Bathroom Installations" },
      { id: 5, label: "Water Heater Installation" },
      { id: 6, label: "Fixture Replacement" },
      { id: 7, label: "Sewer Line Services" },
      { id: 8, label: "Emergency Plumbing" },
    ],
    button: "Send Job Request",
  },
  {
    id: 5,
    profileImg: "/service-requester-dashboard/profile2.svg",
    name: "Laila Al-Farouq",
    occpation: "Expert Plumber",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 20,
    desc: "Reliable plumbing services with quick response time and high-quality repairs.",
    budgetImg: "/service-requester-dashboard/budget.svg",
    budget: "Budget",
    budgetValue: 100,
    locationImg: "/service-requester-dashboard/location.svg",
    location: "Location",
    locationVenue: "Riyadh, Saudi Arabia",
    skills: [
      { id: 1, label: "Pipe Repair" },
      { id: 2, label: "Leak fixing" },
      { id: 3, label: "Drain Cleaning" },
      { id: 4, label: "Bathroom Installations" },
      { id: 5, label: "Water Heater Installation" },
      { id: 6, label: "Fixture Replacement" },
      { id: 7, label: "Sewer Line Services" },
      { id: 8, label: "Emergency Plumbing" },
    ],
    button: "Send Job Request",
  },
  {
    id: 6,
    profileImg: "/service-requester-dashboard/profile2.svg",
    name: "Hassan Al-Mutairi",
    occpation: "Expert Plumber",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 20,
    desc: "Reliable plumbing services with quick response time and high-quality repairs.",
    budgetImg: "/service-requester-dashboard/budget.svg",
    budget: "Budget",
    budgetValue: 100,
    locationImg: "/service-requester-dashboard/location.svg",
    location: "Location",
    locationVenue: "Riyadh, Saudi Arabia",
    skills: [
      { id: 1, label: "Pipe Repair" },
      { id: 2, label: "Leak fixing" },
      { id: 3, label: "Drain Cleaning" },
      { id: 4, label: "Bathroom Installations" },
      { id: 5, label: "Water Heater Installation" },
      { id: 6, label: "Fixture Replacement" },
      { id: 7, label: "Sewer Line Services" },
      { id: 8, label: "Emergency Plumbing" },
    ],
    button: "Send Job Request",
  },
];
