import {
  StatsData,
  ServiceButton,
  ServiceCard,
  StaticContentCard,
  StaticImages,
  StaticTestimonials,
  ServiceProvidersCard,
  IndividualServicesItem,
  IndividualServicesData,
} from "@/interfaces/Landing";

export const statsData: StatsData[] = [
  {
    id: 1,
    value: 100,
    suffix: "+",
    label: "Total Providers",
  },
  {
    id: 2,
    value: 200,
    suffix: "+",
    label: "Job Posted",
  },
  {
    id: 3,
    value: 200,
    suffix: "+",
    label: "Project Completed",
  },
  {
    id: 4,
    value: 100,
    suffix: "+",
    label: "Positive Reviews",
  },
];

export const serviceButtons: ServiceButton[] = [
  { id: 1, label: "Plumbing Services" },
  { id: 2, label: "Electrical Services" },
  { id: 3, label: "Cleaning Services" },
  { id: 4, label: "Tiling & Flooring" },
];

export const plumbingServices: ServiceCard[] = [
  {
    id: 1,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Plumbing Services",
    description: "Pipe Leak Repair - Professional Plumbing Solution",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 156,
    userImg: "/landing/popularservices/user.svg",
    username: "Ahmed Plumber",
    startingAt: "Starting at:",
    price: 130,
    currency: "SAR",
  },
  {
    id: 2,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Plumbing Services",
    description: "Bathroom Fixture Installation - Expert Service",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.8,
    reviews: 142,
    userImg: "/landing/popularservices/user.svg",
    username: "Khalid Plumbing",
    startingAt: "Starting at:",
    price: 150,
    currency: "SAR",
  },
  {
    id: 3,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Plumbing Services",
    description: "Drain Cleaning - Fast & Reliable Service",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 118,
    userImg: "/landing/popularservices/user.svg",
    username: "Omar Pipes",
    startingAt: "Starting at:",
    price: 120,
    currency: "SAR",
  },
  {
    id: 4,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Plumbing Services",
    description: "Water Heater Installation & Repair",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 132,
    userImg: "/landing/popularservices/user.svg",
    username: "Saad Plumbing",
    startingAt: "Starting at:",
    price: 180,
    currency: "SAR",
  },
  {
    id: 5,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Plumbing Services",
    description: "Toilet Repair & Installation - Professional Service",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.8,
    reviews: 127,
    userImg: "/landing/popularservices/user.svg",
    username: "Faisal Plumber",
    startingAt: "Starting at:",
    price: 140,
    currency: "SAR",
  },
  {
    id: 6,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Plumbing Services",
    description: "Sink & Faucet Installation - Expert Plumbing",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 115,
    userImg: "/landing/popularservices/user.svg",
    username: "Majid Pipes",
    startingAt: "Starting at:",
    price: 125,
    currency: "SAR",
  },
  {
    id: 7,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Plumbing Services",
    description: "Sewer Line Repair - Emergency Service",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 138,
    userImg: "/landing/popularservices/user.svg",
    username: "Tariq Plumbing",
    startingAt: "Starting at:",
    price: 200,
    currency: "SAR",
  },
  {
    id: 8,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Plumbing Services",
    description: "Water Filtration System Installation",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.8,
    reviews: 124,
    userImg: "/landing/popularservices/user.svg",
    username: "Nasser Plumber",
    startingAt: "Starting at:",
    price: 170,
    currency: "SAR",
  },
];

export const electricalServices: ServiceCard[] = [
  {
    id: 1,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Electrical Services",
    description: "Electrical Panel Upgrade - Professional Service",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 145,
    userImg: "/landing/popularservices/user.svg",
    username: "Mohammed Electric",
    startingAt: "Starting at:",
    price: 220,
    currency: "SAR",
  },
  {
    id: 2,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Electrical Services",
    description: "Light Fixture Installation - Expert Electrician",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.8,
    reviews: 132,
    userImg: "/landing/popularservices/user.svg",
    username: "Ali Electrical",
    startingAt: "Starting at:",
    price: 150,
    currency: "SAR",
  },
  {
    id: 3,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Electrical Services",
    description: "Outlet & Switch Repair - Fast Service",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 128,
    userImg: "/landing/popularservices/user.svg",
    username: "Fahad Electric",
    startingAt: "Starting at:",
    price: 120,
    currency: "SAR",
  },
  {
    id: 4,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Electrical Services",
    description: "Ceiling Fan Installation & Repair",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 137,
    userImg: "/landing/popularservices/user.svg",
    username: "Youssef Electrical",
    startingAt: "Starting at:",
    price: 160,
    currency: "SAR",
  },
  {
    id: 5,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Electrical Services",
    description: "Home Wiring & Rewiring - Professional Service",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.8,
    reviews: 142,
    userImg: "/landing/popularservices/user.svg",
    username: "Sami Electric",
    startingAt: "Starting at:",
    price: 250,
    currency: "SAR",
  },
  {
    id: 6,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Electrical Services",
    description: "Smart Home Installation - Expert Electrician",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 148,
    userImg: "/landing/popularservices/user.svg",
    username: "Rami Electrical",
    startingAt: "Starting at:",
    price: 300,
    currency: "SAR",
  },
  {
    id: 7,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Electrical Services",
    description: "Electrical Troubleshooting - Emergency Service",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.8,
    reviews: 135,
    userImg: "/landing/popularservices/user.svg",
    username: "Hani Electric",
    startingAt: "Starting at:",
    price: 180,
    currency: "SAR",
  },
  {
    id: 8,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Electrical Services",
    description: "Generator Installation & Maintenance",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 140,
    userImg: "/landing/popularservices/user.svg",
    username: "Waleed Electrical",
    startingAt: "Starting at:",
    price: 350,
    currency: "SAR",
  },
];

export const cleaningServices: ServiceCard[] = [
  {
    id: 1,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Cleaning Services",
    description: "Deep Home Cleaning - Professional Service",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 165,
    userImg: "/landing/popularservices/user.svg",
    username: "Sara Cleaning",
    startingAt: "Starting at:",
    price: 200,
    currency: "SAR",
  },
  {
    id: 2,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Cleaning Services",
    description: "Carpet & Upholstery Cleaning - Expert Service",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.8,
    reviews: 152,
    userImg: "/landing/popularservices/user.svg",
    username: "Layla Clean",
    startingAt: "Starting at:",
    price: 180,
    currency: "SAR",
  },
  {
    id: 3,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Cleaning Services",
    description: "Window Cleaning - Professional & Thorough",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 138,
    userImg: "/landing/popularservices/user.svg",
    username: "Noor Cleaners",
    startingAt: "Starting at:",
    price: 150,
    currency: "SAR",
  },
  {
    id: 4,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Cleaning Services",
    description: "Post-Construction Cleaning - Detailed Service",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 147,
    userImg: "/landing/popularservices/user.svg",
    username: "Amal Cleaning",
    startingAt: "Starting at:",
    price: 300,
    currency: "SAR",
  },
  {
    id: 5,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Cleaning Services",
    description: "Office Cleaning - Regular & Reliable Service",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.8,
    reviews: 155,
    userImg: "/landing/popularservices/user.svg",
    username: "Huda Clean",
    startingAt: "Starting at:",
    price: 250,
    currency: "SAR",
  },
  {
    id: 6,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Cleaning Services",
    description: "Move-In/Move-Out Cleaning - Thorough Service",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 160,
    userImg: "/landing/popularservices/user.svg",
    username: "Fatima Cleaners",
    startingAt: "Starting at:",
    price: 280,
    currency: "SAR",
  },
  {
    id: 7,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Cleaning Services",
    description: "Air Duct & HVAC Cleaning - Professional Service",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.8,
    reviews: 145,
    userImg: "/landing/popularservices/user.svg",
    username: "Reem Clean",
    startingAt: "Starting at:",
    price: 220,
    currency: "SAR",
  },
  {
    id: 8,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Cleaning Services",
    description: "Sanitization & Disinfection - Expert Service",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 158,
    userImg: "/landing/popularservices/user.svg",
    username: "Lina Cleaning",
    startingAt: "Starting at:",
    price: 190,
    currency: "SAR",
  },
];

export const tilingFlooringServices: ServiceCard[] = [
  {
    id: 1,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Tiling & Flooring Services",
    description: "Ceramic Tile Installation - Professional Service",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 155,
    userImg: "/landing/popularservices/user.svg",
    username: "Hassan Tiles",
    startingAt: "Starting at:",
    price: 250,
    currency: "SAR",
  },
  {
    id: 2,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Tiling & Flooring Services",
    description: "Hardwood Floor Installation - Expert Service",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.8,
    reviews: 148,
    userImg: "/landing/popularservices/user.svg",
    username: "Karim Flooring",
    startingAt: "Starting at:",
    price: 300,
    currency: "SAR",
  },
  {
    id: 3,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Tiling & Flooring Services",
    description: "Vinyl & Laminate Flooring - Professional Installation",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.7,
    reviews: 142,
    userImg: "/landing/popularservices/user.svg",
    username: "Ziad Floors",
    startingAt: "Starting at:",
    price: 220,
    currency: "SAR",
  },
  {
    id: 4,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Tiling & Flooring Services",
    description: "Marble & Granite Installation - Luxury Service",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 160,
    userImg: "/landing/popularservices/user.svg",
    username: "Jamal Tiles",
    startingAt: "Starting at:",
    price: 400,
    currency: "SAR",
  },
  {
    id: 5,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Tiling & Flooring Services",
    description: "Bathroom Tile Installation - Waterproof Service",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.8,
    reviews: 150,
    userImg: "/landing/popularservices/user.svg",
    username: "Adel Flooring",
    startingAt: "Starting at:",
    price: 270,
    currency: "SAR",
  },
  {
    id: 6,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Tiling & Flooring Services",
    description: "Floor Repair & Restoration - Expert Service",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 152,
    userImg: "/landing/popularservices/user.svg",
    username: "Malik Tiles",
    startingAt: "Starting at:",
    price: 230,
    currency: "SAR",
  },
  {
    id: 7,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Tiling & Flooring Services",
    description: "Kitchen Backsplash Installation - Professional Service",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.8,
    reviews: 145,
    userImg: "/landing/popularservices/user.svg",
    username: "Bilal Flooring",
    startingAt: "Starting at:",
    price: 210,
    currency: "SAR",
  },
  {
    id: 8,
    coverImg: "/landing/popularservices/coverimage.svg",
    title: "Tiling & Flooring Services",
    description: "Epoxy Flooring - Industrial & Residential Service",
    starImg: "/landing/popularservices/star.svg",
    rating: 4.9,
    reviews: 158,
    userImg: "/landing/popularservices/user.svg",
    username: "Tamer Tiles",
    startingAt: "Starting at:",
    price: 320,
    currency: "SAR",
  },
];

export const serviceDataMap: Record<string, ServiceCard[]> = {
  "Plumbing Services": plumbingServices,
  "Electrical Services": electricalServices,
  "Cleaning Services": cleaningServices,
  "Tiling & Flooring Services": tilingFlooringServices,
};

export const staticContentData: StaticContentCard[] = [
  {
    id: 1,
    icon: "/landing/needsomething/search.svg",
    title: "Post A Job",
    desc: "Post your job for free and let skilled professionals come to you with offers.",
  },
  {
    id: 2,
    icon: "/landing/needsomething/freelancer.svg",
    title: "Choose Freelancers",
    desc: "Browse through verified service providers, check reviews, and select the best freelancer.",
  },
  {
    id: 3,
    icon: "/landing/needsomething/safety.svg",
    title: "Pay Safely",
    desc: "Your money is only released once the job is done to your satisfaction.",
  },
];

export const imagesData: StaticImages[] = [
  {
    id: 1,
    icon: "/landing/categories/plumbing.svg",
    name: "Plumbing",
    desc: "Pipe Repair & Fittings",
  },
  {
    id: 2,
    icon: "/landing/categories/electric.svg",
    name: "Electrical Services",
    desc: "Wiring & Installations",
  },
  {
    id: 3,
    icon: "/landing/categories/cleaning.svg",
    name: "Cleaning Services",
    desc: "Deep Cleaning & Sanitization",
  },
  {
    id: 4,
    icon: "/landing/categories/carpentry.svg",
    name: "Carpentry",
    desc: "Custom Furniture & Repairs",
  },
  {
    id: 5,
    icon: "/landing/categories/tiling.svg",
    name: "Tiling & Flooring",
    desc: "Floor Installation & Polishing",
  },
];

export const staticTestimonials: StaticTestimonials[] = [
  {
    id: 1,
    icon: "/landing/categories/check-circle.svg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing",
  },
  {
    id: 2,
    icon: "/landing/categories/check-circle.svg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing",
  },
  {
    id: 3,
    icon: "/landing/categories/check-circle.svg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing",
  },
];

export const serviceProvidersData: ServiceProvidersCard[] = [
  {
    id: 1,
    icon: "/landing/categories/user2.svg",
    name: "Khalid Al-Qahtani",
    profession: "Carpenter",
  },
  {
    id: 2,
    icon: "/landing/popularservices/user.svg",
    name: "Abdullah Al-Harbi",
    profession: "Carpenter",
  },
  {
    id: 3,
    icon: "/landing/categories/user3.svg",
    name: "Abdullah Al-Harbi",
    profession: "Carpenter",
  },
  {
    id: 4,
    icon: "/landing/categories/user4.svg",
    name: "Abdullah Al-Harbi",
    profession: "Carpenter",
  },
];

export const individualServices: IndividualServicesItem[] = [
  {
    id: 1,
    name: "Emergency Plumbing",
  },
  {
    id: 2,
    name: "Water Supply",
  },
];

export const individualServicesData: IndividualServicesData[] = [
  {
    id: 1,
    key: "Location",
    value: "Saudia",
  },
  {
    id: 2,
    key: "Rate",
    value: 130,
    suffix: "SAR",
  },
  {
    id: 3,
    key: "Job Success",
    value: 100,
    suffix: "%",
  },
];
