import {
  JobRequestCard,
  OrderCard,
  ProviderDisputes,
  ProviderEarnings,
} from "@/interfaces/Service-Provider-Dashboard";
import {
  AnalyticsCard,
  FAQ,
  MenuSection,
} from "@/interfaces/Service-Requester-Dashboard";

export const providerMenuLinks: MenuSection[] = [
  {
    id: 1,
    title: "General",
    links: [
      {
        id: 1,
        icon: "/service-requester-dashboard/dashboard.svg",
        icon2: "/service-requester-dashboard/dashboard2.svg",
        label: "Dashboard",
        url: "?view=dashboard",
      },
      {
        id: 2,
        icon: "/service-requester-dashboard/jobs.svg",
        icon2: "/service-requester-dashboard/jobs2.svg",
        label: "Orders",
        url: "?view=orders",
      },
      {
        id: 3,
        icon: "/service-requester-dashboard/disputes.svg",
        icon2: "/service-requester-dashboard/disputes2.svg",
        label: "Disputes",
        url: "?view=disputes",
      },
      {
        id: 4,
        icon: "/service-requester-dashboard/messages.svg",
        icon2: "/service-requester-dashboard/messages2.svg",
        label: "Messages",
        url: "?view=messages",
      },
      {
        id: 5,
        icon: "/service-provider-dashboard/earnings.svg",
        icon2: "/service-provider-dashboard/earnings2.svg",
        label: "Earnings",
        url: "?view=earnings",
      },
    ],
  },
  {
    id: 2,
    title: "Tools",
    links: [
      {
        id: 1,
        icon: "/service-requester-dashboard/payment.svg",
        icon2: "/service-requester-dashboard/payment2.svg",
        label: "Billing",
        url: "?view=billing",
      },
      {
        id: 2,
        icon: "/service-requester-dashboard/setting.svg",
        icon2: "/service-requester-dashboard/setting2.svg",
        label: "Settings",
        url: "?view=settings",
      },
      {
        id: 3,
        icon: "/service-requester-dashboard/faq.svg",
        icon2: "/service-requester-dashboard/faq2.svg",
        label: "FAQs",
        url: "?view=faqs",
      },
      {
        id: 4,
        icon: "/service-requester-dashboard/logout.svg",
        icon2: "/service-requester-dashboard/logout2.svg",
        label: "Logout",
        url: "#",
      },
    ],
  },
];

export const providerOrderAnalyticsData: AnalyticsCard[] = [
  {
    id: 1,
    label: "Completed Orders",
    value: 20,
  },
  {
    id: 2,
    label: "Average Selling Price",
    value: 150,
    unit: "SAR",
  },
  {
    id: 3,
    label: "Order Completion Rate",
    value: 99,
    unit: "%",
  },
  {
    id: 4,
    label: "Earning to Date",
    value: 500,
    unit: "SAR",
  },
];

export const dataFilters = [
  {
    id: 1,
    label: "Last Year",
  },
  {
    id: 2,
    label: "This Year",
  },
  {
    id: 3,
    label: "Last 3 Months",
  },
  {
    id: 4,
    label: "Last 6 Months",
  },
];

export const jobRequestCardData: JobRequestCard[] = [
  {
    value: 20,
    time: "6.32",
    title: "Plumbing Repair for Home",
    budget: "150 SAR",
    address: "Villa 23, Street 12, Al Muruj District, Riyadh",
    image: "/service-requester-dashboard/profile.svg",
    name: "Ahmad Khan",
    rating: 4.9,
    reviews: 20,
  },
  {
    value: 20,
    time: "3.15",
    title: "Air Conditioner Maintenance",
    budget: "200 SAR",
    address: "Building 5, King Fahd Road, Jeddah",
    image: "/service-requester-dashboard/profile.svg",
    name: "Sami Ullah",
    rating: 4.7,
    reviews: 35,
  },
  {
    value: 40,
    time: "8.45",
    title: "Kitchen Sink Installation",
    budget: "180 SAR",
    address: "Flat 8B, Corniche Area, Dammam",
    image: "/service-requester-dashboard/profile.svg",
    name: "Fatima Noor",
    rating: 5.0,
    reviews: 42,
  },
];

export const searchOptions = ["Latest", "Oldest"];

export const activeOrdersData: OrderCard[] = [
  {
    id: 1,
    image: "/service-provider-dashboard/order-image.svg",
    title: "House Cleaning & Roofing Maintenance Needed",
    requester: "Hired By",
    orderRequesterName: "Saud Al-Faisal",
    price: "Order Price",
    orderPrice: 200,
    duration: "Duration",
    orderDuration: 3,
    orderStarted: "Order Started",
    orderStartedDate: "Mar 05, 2025",
    status: "Ongoing",
    view: "View",
  },
  {
    id: 2,
    image: "/service-provider-dashboard/order-image.svg",
    title: "Garden Landscaping Required",
    requester: "Hired By",
    orderRequesterName: "Layla Al-Sabah",
    price: "Order Price",
    orderPrice: 350,
    duration: "Duration",
    orderDuration: 5,
    orderStarted: "Order Started",
    orderStartedDate: "Feb 20, 2025",
    status: "Ongoing",
    view: "View",
  },
  {
    id: 3,
    image: "/service-provider-dashboard/order-image.svg",
    title: "Swimming Pool Deep Cleaning",
    requester: "Hired By",
    orderRequesterName: "Omar Al-Fahad",
    price: "Order Price",
    orderPrice: 500,
    duration: "Duration",
    orderDuration: 2,
    orderStarted: "Order Started",
    orderStartedDate: "Jan 12, 2025",
    status: "Ongoing",
    view: "View",
  },
  {
    id: 4,
    image: "/service-provider-dashboard/order-image.svg",
    title: "Electrical Wiring Fix Needed",
    requester: "Hired By",
    orderRequesterName: "Noor Al-Rashid",
    price: "Order Price",
    orderPrice: 150,
    duration: "Duration",
    orderDuration: 1,
    orderStarted: "Order Started",
    orderStartedDate: "Mar 01, 2025",
    status: "Ongoing",
    view: "View",
  },
  {
    id: 5,
    image: "/service-provider-dashboard/order-image.svg",
    title: "Painting & Wall Restoration",
    requester: "Hired By",
    orderRequesterName: "Yousef Al-Harbi",
    price: "Order Price",
    orderPrice: 400,
    duration: "Duration",
    orderDuration: 4,
    orderStarted: "Order Started",
    orderStartedDate: "Mar 10, 2025",
    status: "Ongoing",
    view: "View",
  },
  {
    id: 6,
    image: "/service-provider-dashboard/order-image.svg",
    title: "Interior Design Consultation",
    requester: "Hired By",
    orderRequesterName: "Salma Al-Najjar",
    price: "Order Price",
    orderPrice: 700,
    duration: "Duration",
    orderDuration: 2,
    orderStarted: "Order Started",
    orderStartedDate: "Feb 28, 2025",
    status: "Ongoing",
    view: "View",
  },
  {
    id: 7,
    image: "/service-provider-dashboard/order-image.svg",
    title: "AC Unit Repair & Maintenance",
    requester: "Hired By",
    orderRequesterName: "Ahmed Al-Qassim",
    price: "Order Price",
    orderPrice: 180,
    duration: "Duration",
    orderDuration: 1,
    orderStarted: "Order Started",
    orderStartedDate: "Mar 06, 2025",
    status: "Ongoing",
    view: "View",
  },
  {
    id: 8,
    image: "/service-provider-dashboard/order-image.svg",
    title: "Security Camera Installation",
    requester: "Hired By",
    orderRequesterName: "Fatima Al-Khalifa",
    price: "Order Price",
    orderPrice: 600,
    duration: "Duration",
    orderDuration: 2,
    orderStarted: "Order Started",
    orderStartedDate: "Mar 02, 2025",
    status: "Ongoing",
    view: "View",
  },
  {
    id: 9,
    image: "/service-provider-dashboard/order-image.svg",
    title: "Window Glass Replacement",
    requester: "Hired By",
    orderRequesterName: "Khalid Al-Sultan",
    price: "Order Price",
    orderPrice: 250,
    duration: "Duration",
    orderDuration: 2,
    orderStarted: "Order Started",
    orderStartedDate: "Feb 15, 2025",
    status: "Ongoing",
    view: "View",
  },
  {
    id: 10,
    image: "/service-provider-dashboard/order-image.svg",
    title: "Roof Water Proofing Required",
    requester: "Hired By",
    orderRequesterName: "Aisha Al-Hamdan",
    price: "Order Price",
    orderPrice: 320,
    duration: "Duration",
    orderDuration: 3,
    orderStarted: "Order Started",
    orderStartedDate: "Feb 10, 2025",
    status: "Ongoing",
    view: "View",
  },
];

export const completedOrdersData: OrderCard[] = [
  {
    id: 1,
    image: "/service-provider-dashboard/order-image.svg",
    title: "House Cleaning & Roofing Maintenance Needed",
    requester: "Hired By",
    orderRequesterName: "Saud Al-Faisal",
    price: "Order Price",
    orderPrice: 200,
    duration: "Duration",
    orderDuration: 3,
    orderStarted: "Order Started",
    orderStartedDate: "Mar 05, 2025",
    status: "Completed",
    view: "View",
  },
  {
    id: 2,
    image: "/service-provider-dashboard/order-image.svg",
    title: "Garden Landscaping Required",
    requester: "Hired By",
    orderRequesterName: "Layla Al-Sabah",
    price: "Order Price",
    orderPrice: 350,
    duration: "Duration",
    orderDuration: 5,
    orderStarted: "Order Started",
    orderStartedDate: "Feb 20, 2025",
    status: "Completed",
    view: "View",
  },
  {
    id: 3,
    image: "/service-provider-dashboard/order-image.svg",
    title: "Swimming Pool Deep Cleaning",
    requester: "Hired By",
    orderRequesterName: "Omar Al-Fahad",
    price: "Order Price",
    orderPrice: 500,
    duration: "Duration",
    orderDuration: 2,
    orderStarted: "Order Started",
    orderStartedDate: "Jan 12, 2025",
    status: "Completed",
    view: "View",
  },
  {
    id: 4,
    image: "/service-provider-dashboard/order-image.svg",
    title: "Electrical Wiring Fix Needed",
    requester: "Hired By",
    orderRequesterName: "Noor Al-Rashid",
    price: "Order Price",
    orderPrice: 150,
    duration: "Duration",
    orderDuration: 1,
    orderStarted: "Order Started",
    orderStartedDate: "Mar 01, 2025",
    status: "Completed",
    view: "View",
  },
  {
    id: 5,
    image: "/service-provider-dashboard/order-image.svg",
    title: "Painting & Wall Restoration",
    requester: "Hired By",
    orderRequesterName: "Yousef Al-Harbi",
    price: "Order Price",
    orderPrice: 400,
    duration: "Duration",
    orderDuration: 4,
    orderStarted: "Order Started",
    orderStartedDate: "Mar 10, 2025",
    status: "Completed",
    view: "View",
  },
  {
    id: 6,
    image: "/service-provider-dashboard/order-image.svg",
    title: "Interior Design Consultation",
    requester: "Hired By",
    orderRequesterName: "Salma Al-Najjar",
    price: "Order Price",
    orderPrice: 700,
    duration: "Duration",
    orderDuration: 2,
    orderStarted: "Order Started",
    orderStartedDate: "Feb 28, 2025",
    status: "Completed",
    view: "View",
  },
  {
    id: 7,
    image: "/service-provider-dashboard/order-image.svg",
    title: "AC Unit Repair & Maintenance",
    requester: "Hired By",
    orderRequesterName: "Ahmed Al-Qassim",
    price: "Order Price",
    orderPrice: 180,
    duration: "Duration",
    orderDuration: 1,
    orderStarted: "Order Started",
    orderStartedDate: "Mar 06, 2025",
    status: "Completed",
    view: "View",
  },
  {
    id: 8,
    image: "/service-provider-dashboard/order-image.svg",
    title: "Security Camera Installation",
    requester: "Hired By",
    orderRequesterName: "Fatima Al-Khalifa",
    price: "Order Price",
    orderPrice: 600,
    duration: "Duration",
    orderDuration: 2,
    orderStarted: "Order Started",
    orderStartedDate: "Mar 02, 2025",
    status: "Completed",
    view: "View",
  },
  {
    id: 9,
    image: "/service-provider-dashboard/order-image.svg",
    title: "Window Glass Replacement",
    requester: "Hired By",
    orderRequesterName: "Khalid Al-Sultan",
    price: "Order Price",
    orderPrice: 250,
    duration: "Duration",
    orderDuration: 2,
    orderStarted: "Order Started",
    orderStartedDate: "Feb 15, 2025",
    status: "Completed",
    view: "View",
  },
  {
    id: 10,
    image: "/service-provider-dashboard/order-image.svg",
    title: "Roof Water Proofing Required",
    requester: "Hired By",
    orderRequesterName: "Aisha Al-Hamdan",
    price: "Order Price",
    orderPrice: 320,
    duration: "Duration",
    orderDuration: 3,
    orderStarted: "Order Started",
    orderStartedDate: "Feb 10, 2025",
    status: "Completed",
    view: "View",
  },
];

export const cancelledOrdersData: OrderCard[] = [
  {
    id: 1,
    image: "/service-provider-dashboard/order-image.svg",
    title: "House Cleaning & Roofing Maintenance Needed",
    requester: "Hired By",
    orderRequesterName: "Saud Al-Faisal",
    price: "Order Price",
    orderPrice: 200,
    duration: "Duration",
    orderDuration: 3,
    orderStarted: "Order Started",
    orderStartedDate: "Mar 05, 2025",
    status: "Cancelled",
    view: "View",
  },
  {
    id: 2,
    image: "/service-provider-dashboard/order-image.svg",
    title: "Garden Landscaping Required",
    requester: "Hired By",
    orderRequesterName: "Layla Al-Sabah",
    price: "Order Price",
    orderPrice: 350,
    duration: "Duration",
    orderDuration: 5,
    orderStarted: "Order Started",
    orderStartedDate: "Feb 20, 2025",
    status: "Cancelled",
    view: "View",
  },
  {
    id: 3,
    image: "/service-provider-dashboard/order-image.svg",
    title: "Swimming Pool Deep Cleaning",
    requester: "Hired By",
    orderRequesterName: "Omar Al-Fahad",
    price: "Order Price",
    orderPrice: 500,
    duration: "Duration",
    orderDuration: 2,
    orderStarted: "Order Started",
    orderStartedDate: "Jan 12, 2025",
    status: "Cancelled",
    view: "View",
  },
  {
    id: 4,
    image: "/service-provider-dashboard/order-image.svg",
    title: "Electrical Wiring Fix Needed",
    requester: "Hired By",
    orderRequesterName: "Noor Al-Rashid",
    price: "Order Price",
    orderPrice: 150,
    duration: "Duration",
    orderDuration: 1,
    orderStarted: "Order Started",
    orderStartedDate: "Mar 01, 2025",
    status: "Cancelled",
    view: "View",
  },
  {
    id: 5,
    image: "/service-provider-dashboard/order-image.svg",
    title: "Painting & Wall Restoration",
    requester: "Hired By",
    orderRequesterName: "Yousef Al-Harbi",
    price: "Order Price",
    orderPrice: 400,
    duration: "Duration",
    orderDuration: 4,
    orderStarted: "Order Started",
    orderStartedDate: "Mar 10, 2025",
    status: "Cancelled",
    view: "View",
  },
  {
    id: 6,
    image: "/service-provider-dashboard/order-image.svg",
    title: "Interior Design Consultation",
    requester: "Hired By",
    orderRequesterName: "Salma Al-Najjar",
    price: "Order Price",
    orderPrice: 700,
    duration: "Duration",
    orderDuration: 2,
    orderStarted: "Order Started",
    orderStartedDate: "Feb 28, 2025",
    status: "Cancelled",
    view: "View",
  },
  {
    id: 7,
    image: "/service-provider-dashboard/order-image.svg",
    title: "AC Unit Repair & Maintenance",
    requester: "Hired By",
    orderRequesterName: "Ahmed Al-Qassim",
    price: "Order Price",
    orderPrice: 180,
    duration: "Duration",
    orderDuration: 1,
    orderStarted: "Order Started",
    orderStartedDate: "Mar 06, 2025",
    status: "Cancelled",
    view: "View",
  },
  {
    id: 8,
    image: "/service-provider-dashboard/order-image.svg",
    title: "Security Camera Installation",
    requester: "Hired By",
    orderRequesterName: "Fatima Al-Khalifa",
    price: "Order Price",
    orderPrice: 600,
    duration: "Duration",
    orderDuration: 2,
    orderStarted: "Order Started",
    orderStartedDate: "Mar 02, 2025",
    status: "Cancelled",
    view: "View",
  },
  {
    id: 9,
    image: "/service-provider-dashboard/order-image.svg",
    title: "Window Glass Replacement",
    requester: "Hired By",
    orderRequesterName: "Khalid Al-Sultan",
    price: "Order Price",
    orderPrice: 250,
    duration: "Duration",
    orderDuration: 2,
    orderStarted: "Order Started",
    orderStartedDate: "Feb 15, 2025",
    status: "Cancelled",
    view: "View",
  },
  {
    id: 10,
    image: "/service-provider-dashboard/order-image.svg",
    title: "Roof Water Proofing Required",
    requester: "Hired By",
    orderRequesterName: "Aisha Al-Hamdan",
    price: "Order Price",
    orderPrice: 320,
    duration: "Duration",
    orderDuration: 3,
    orderStarted: "Order Started",
    orderStartedDate: "Feb 10, 2025",
    status: "Cancelled",
    view: "View",
  },
];

export const providerDisputesData: ProviderDisputes[] = [
  {
    refNumber: "11564",
    employerName: "Haider Ali",
    date: "2/5/2025",
    amount: 113,
    currency: "SAR",
    status: "Disputed",
  },
  {
    refNumber: "11572",
    employerName: "Farooq Khan",
    date: "13/4/2025",
    amount: 324,
    currency: "SAR",
    status: "Disputed",
  },
  {
    refNumber: "11529",
    employerName: "Haider Ali",
    date: "13/4/2025",
    amount: 214,
    currency: "SAR",
    status: "Disputed",
  },
  {
    refNumber: "11292",
    employerName: "Farooq Khan",
    date: "13/4/2025",
    amount: 121,
    currency: "SAR",
    status: "Disputed",
  },
  {
    refNumber: "13810",
    employerName: "Haider Ali",
    date: "13/4/2025",
    amount: 140,
    currency: "SAR",
    status: "Disputed",
  },
  {
    refNumber: "11823",
    employerName: "Sana Mir",
    date: "10/4/2025",
    amount: 190,
    currency: "SAR",
    status: "Disputed",
  },
  {
    refNumber: "11756",
    employerName: "Ahmed Raza",
    date: "11/4/2025",
    amount: 256,
    currency: "SAR",
    status: "Disputed",
  },
  {
    refNumber: "11478",
    employerName: "Zara Sheikh",
    date: "9/4/2025",
    amount: 330,
    currency: "SAR",
    status: "Disputed",
  },
  {
    refNumber: "11634",
    employerName: "Imran Malik",
    date: "12/4/2025",
    amount: 275,
    currency: "SAR",
    status: "Disputed",
  },
  {
    refNumber: "11901",
    employerName: "Ayesha Khan",
    date: "8/4/2025",
    amount: 145,
    currency: "SAR",
    status: "Disputed",
  },
  {
    refNumber: "11390",
    employerName: "Usman Tariq",
    date: "7/4/2025",
    amount: 198,
    currency: "SAR",
    status: "Disputed",
  },
  {
    refNumber: "11127",
    employerName: "Rabia Yousaf",
    date: "6/4/2025",
    amount: 220,
    currency: "SAR",
    status: "Disputed",
  },
  {
    refNumber: "12003",
    employerName: "Noman Shah",
    date: "5/4/2025",
    amount: 310,
    currency: "SAR",
    status: "Disputed",
  },
  {
    refNumber: "12114",
    employerName: "Laiba Noor",
    date: "4/4/2025",
    amount: 175,
    currency: "SAR",
    status: "Disputed",
  },
  {
    refNumber: "12225",
    employerName: "Bilal Ansari",
    date: "3/4/2025",
    amount: 200,
    currency: "SAR",
    status: "Disputed",
  },
];

export const providerEarningAnalyticsData: AnalyticsCard[] = [
  {
    id: 1,
    label: "Available Balance",
    value: 200,
    unit: "SAR",
  },
  {
    id: 2,
    label: "Earnings To Date",
    value: 640,
    unit: "SAR",
  },
  {
    id: 3,
    label: "Payment For Active Jobs",
    value: 140,
    unit: "SAR",
  },
  {
    id: 4,
    label: "Payments Being Cleared",
    value: 300,
    unit: "SAR",
  },
];

export const providerEarningsData: ProviderEarnings[] = [
  {
    date: "3/5/2025",
    description: "Order",
    from: "Saud Al–Faisal",
    orderId: "MO21364BFE6C4",
    amount: 113,
  },
  {
    date: "2/5/2025",
    description: "Order",
    from: "Saud Al–Faisal",
    orderId: "MO719FF4EA781",
    amount: 230,
  },
  {
    date: "13/4/2025",
    description: "Order",
    from: "Saud Al–Faisal",
    orderId: "MO82070032602",
    amount: 80,
  },
  {
    date: "25/2/2025",
    description: "Order",
    from: "Saud Al–Faisal",
    orderId: "MO11371D97DC5",
    amount: 250,
  },
  {
    date: "8/3/2025",
    description: "Order",
    from: "Saud Al–Faisal",
    orderId: "MO719UH2EY267",
    amount: 270,
  },
  {
    date: "2/5/2025",
    description: "Order",
    from: "Saud Al–Faisal",
    orderId: "MO719FF4EA781",
    amount: 230,
  },
  {
    date: "3/5/2025",
    description: "Order",
    from: "Saud Al–Faisal",
    orderId: "MO21364BFE6C4",
    amount: 113,
  },
  {
    date: "13/4/2025",
    description: "Order",
    from: "Saud Al–Faisal",
    orderId: "MO82070032602",
    amount: 80,
  },
  {
    date: "25/2/2025",
    description: "Order",
    from: "Saud Al–Faisal",
    orderId: "MO11371D97DC5",
    amount: 250,
  },
  {
    date: "8/3/2025",
    description: "Order",
    from: "Saud Al–Faisal",
    orderId: "MO719UH2EY267",
    amount: 270,
  },
  {
    date: "3/5/2025",
    description: "Order",
    from: "Saud Al–Faisal",
    orderId: "MO21364BFE6C4",
    amount: 113,
  },
  {
    date: "2/5/2025",
    description: "Order",
    from: "Saud Al–Faisal",
    orderId: "MO719FF4EA781",
    amount: 230,
  },
  {
    date: "13/4/2025",
    description: "Order",
    from: "Saud Al–Faisal",
    orderId: "MO82070032602",
    amount: 80,
  },
  {
    date: "25/2/2025",
    description: "Order",
    from: "Saud Al–Faisal",
    orderId: "MO11371D97DC5",
    amount: 250,
  },
  {
    date: "8/3/2025",
    description: "Order",
    from: "Saud Al–Faisal",
    orderId: "MO719UH2EY267",
    amount: 270,
  },
];

export const providerFaqData: FAQ[] = [
  {
    id: 1,
    title: "How do I find and apply for service requests?",
    desc: "Once your account is verified, you can browse available jobs in your category from the 'Browse Jobs' section. Simply click 'Apply' on jobs that match your skills and submit a proposal to the requester.",
  },
  {
    id: 2,
    title: "What is the verification process for service providers?",
    desc: "All service providers are required to complete a profile verification which includes identity verification, skill assessment, and portfolio submission. This builds trust and improves your chances of getting hired.",
  },
  {
    id: 3,
    title: "How do I get paid for completed jobs?",
    desc: "Payments are securely processed through the platform. Once a job is marked complete and approved by the requester, funds will be released to your wallet. You can then withdraw to your preferred payment method.",
  },
  {
    id: 4,
    title: "What should I do if a requester is unresponsive?",
    desc: "If a requester does not respond after you’ve applied or during a job, you can report the issue from the job page. Our support team will look into the matter and help facilitate communication or reassign the task.",
  },
  {
    id: 5,
    title: "Can I cancel a job after accepting it?",
    desc: "Yes, but cancellations may affect your reliability rating. If you must cancel, communicate with the requester first and explain the situation. Repeated cancellations without valid reasons may result in penalties.",
  },
  {
    id: 6,
    title: "How can I improve my chances of getting hired?",
    desc: "Maintain a complete and professional profile, respond quickly to job postings, provide competitive quotes, and build a strong reputation by delivering high-quality work and earning positive reviews.",
  },
];
